"use client";
import { FormEvent, useEffect, useState } from "react";
export default function BranchesClient({platform}:{platform:{shortName:string}}) {
  const [data,setData]=useState<any[]>([]),[members,setMembers]=useState<any[]>([]),[assignments,setAssignments]=useState<any[]>([]),[f,setF]=useState({name:"",location:"",phone:"",managerUserId:""}),[message,setMessage]=useState("");
  const load=()=>Promise.all([fetch("/api/branches").then(r=>r.json()),fetch("/api/workspace").then(r=>r.json())]).then(([b,w])=>{setData(b.branches||[]);setAssignments(b.assignments||[]);setMembers(w.members||[])});
  useEffect(()=>{load()},[]);
  async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const r=await fetch("/api/branches",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(f)}),j=await r.json();setMessage(r.ok?"Branch created and ready for property assignment.":j.error);if(r.ok){setF({name:"",location:"",phone:"",managerUserId:""});load()}}
  async function toggle(x:any){await fetch("/api/branches",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:x.id,active:!x.active})});load()}
  async function assign(branchId:string,userId:string,assigned:boolean){const r=await fetch("/api/branches",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action:"assign",branchId,userId,assigned})}),j=await r.json();setMessage(r.ok?(assigned?"Member restricted to assigned branches.":"Branch access removed."):j.error);load()}
  return <main className="branches-page"><nav><a href="/">← Workspace</a><strong>{platform.shortName} <small>Agency structure</small></strong></nav><header><span>LOCAL OWNERSHIP · SHARED SYSTEM</span><h1>Branches</h1><p>Assign listings and managers to real agency offices, with server-enforced branch access for selected team members.</p></header><section><div className="branch-list">{data.map(x=><article key={x.id}><i>{x.name.slice(0,2).toUpperCase()}</i><div><small>{x.active?"ACTIVE BRANCH":"INACTIVE"}</small><h2>{x.name}</h2><p>{x.location||"Location not set"} · {x.phone||"No phone"}</p><span>{x.managerEmail||"No manager"} · {x.properties} properties</span><label>Branch-scoped member<select aria-label={`Assign a member to ${x.name}`} defaultValue="" onChange={e=>{if(e.target.value)assign(x.id,e.target.value,true);e.target.value=""}}><option value="">Choose member…</option>{members.map(m=><option value={m.userId} key={m.userId}>{m.email}</option>)}</select></label>{assignments.filter(a=>a.branchId===x.id).map(a=><button key={a.userId} onClick={()=>assign(x.id,a.userId,false)}>Remove {a.email}</button>)}</div><button onClick={()=>toggle(x)}>{x.active?"Deactivate":"Reactivate"}</button></article>)}{!data.length&&<p>No branches yet. Create the agency’s first office.</p>}</div><form onSubmit={create}><span>NEW BRANCH</span><h2>Add an office</h2><label>Branch name<input required value={f.name} onChange={e=>setF({...f,name:e.target.value})} placeholder="Borrowdale office"/></label><label>Location<input value={f.location} onChange={e=>setF({...f,location:e.target.value})} placeholder="Harare"/></label><label>Phone<input type="tel" value={f.phone} onChange={e=>setF({...f,phone:e.target.value})} placeholder="+263…"/></label><label>Manager<select value={f.managerUserId} onChange={e=>setF({...f,managerUserId:e.target.value})}><option value="">No manager yet</option>{members.map(x=><option value={x.userId} key={x.userId}>{x.email}</option>)}</select></label><button>Create branch</button>{message&&<p role="status">{message}</p>}</form></section></main>;
}
