import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const read = path => readFile(new URL(path, import.meta.url), "utf8");

test("super admin dashboard exposes platform-wide command, settings and evidence controls", async () => {
  const [client, route, css] = await Promise.all([
    read("../app/admin/platform-admin-client.tsx"),
    read("../app/api/platform/route.ts"),
    read("../app/globals.css"),
  ]);
  assert.match(client, /Super admin command centre/);
  assert.match(client, /Platform settings/);
  assert.match(client, /GLOBAL PLATFORM CONFIGURATION/);
  assert.match(client, /supportEmail/);
  assert.match(client, /accentColor/);
  assert.match(client, /tenantDomainSuffix/);
  assert.match(client, /CONTROL PLANE AUDITS/);
  assert.match(client, /Platform health/);
  assert.match(client, /Sign out/);
  assert.match(client, /Issue invoice/);
  assert.match(client, /Opening control plane/);
  assert.match(client, /Refresh console/);
  assert.match(client, /platform-nav-group/);
  assert.match(client, /platform-page-strip/);
  assert.match(client, /platform-admin-compact/);
  assert.match(client, /AdminThemeVars/);
  assert.match(client, /"--admin-brand": data\.settings\?\.primaryColor/);
  assert.match(client, /"--admin-accent": data\.settings\?\.accentColor/);
  assert.match(client, /normaliseHex/);
  assert.match(client, /type="color"/);
  assert.match(client, /cache: "no-store"/);
  assert.match(client, /result\.settings/);
  assert.match(client, /const showPageStrip = tab === "settings"/);
  assert.match(client, /platform-empty-panel/);
  assert.match(client, /No agencies found/);
  assert.match(client, /No plan versions yet/);
  assert.match(client, /Brand System/);
  assert.match(client, /Support Desk/);
  assert.match(client, /Regional Defaults/);
  assert.match(client, /Public Routing/);
  assert.match(client, /platform-analytics-grid/);
  assert.match(client, /platform-donut/);
  assert.match(client, /conic-gradient\(var\(--admin-brand,#153b34\)/);
  assert.match(client, /var\(--admin-accent,#e6bd5f\) 0deg/);
  assert.doesNotMatch(client, /#27c5b8/);
  assert.doesNotMatch(client, /#f0c24b/);
  assert.match(client, /WEEKLY PLATFORM INSIGHTS/);
  assert.match(route, /update_platform_settings/);
  assert.match(route, /accent_color AS accentColor/);
  assert.match(route, /accent_color=\?/);
  assert.match(route, /const hex/);
  assert.match(route, /settings: await platformSettingsRow\(\)/);
  assert.match(route, /\["super_admin"\]/);
  assert.match(route, /platform\.settings\.updated/);
  assert.match(route, /publicIntake10m/);
  assert.match(route, /recentPlatformAudits/);
  assert.match(css, /platform-shell\{[^}]*overflow-y:auto/);
  assert.match(css, /platform-operator-card/);
  assert.match(css, /platform-admin-loading/);
  assert.match(css, /platform-side-status/);
  assert.match(css, /platform-control-card/);
  assert.match(css, /platform-page-strip/);
  assert.match(css, /SUPER ADMIN RESPONSIVE PRODUCT SHELL/);
  assert.match(css, /max-width:980px/);
  assert.match(css, /platform-shell\{position:sticky!important/);
  assert.match(css, /platform-agency-row\{min-width:0!important/);
  assert.match(css, /max-width:620px/);
  assert.match(css, /SUPER ADMIN EXECUTIVE VISUAL SYSTEM/);
  assert.match(css, /SUPER ADMIN COMPACT REVAMP/);
  assert.match(css, /SUPER ADMIN STRUCTURE POLISH/);
  assert.match(css, /platform-admin-compact/);
  assert.match(css, /Georgia,serif!important/);
  assert.match(css, /platform-empty-panel/);
  assert.match(css, /SUPER ADMIN SETTINGS WORKSPACE/);
  assert.match(css, /SUPER ADMIN PLATFORM THEME BINDING/);
  assert.match(css, /--admin-brand-deep:color-mix\(in srgb,var\(--admin-brand,#153b34\) 58%,#000\)/);
  assert.match(css, /platform-shell\{background:linear-gradient\(180deg,var\(--admin-brand,#153b34\),var\(--admin-brand-deep\)\)/);
  assert.match(css, /var\(--admin-brand,#153b34\)/);
  assert.match(css, /var\(--admin-accent,#e6bd5f\)/);
  assert.match(css, /platform-operator-card\{border-color:color-mix\(in srgb,var\(--admin-accent,#e6bd5f\)/);
  assert.match(css, /platform-operator-card small\{background:var\(--admin-accent,#e6bd5f\)/);
  assert.match(css, /color-mix\(in srgb,var\(--admin-brand,#153b34\)/);
  assert.match(css, /platform-config-grid fieldset/);
  assert.match(css, /platform-analytics-grid/);
  assert.match(css, /platform-bars-card/);
  assert.match(css, /platform-settings-grid label/);
});
