import assert from"node:assert/strict";import{readFile}from"node:fs/promises";import test from"node:test";const read=p=>readFile(new URL(p,import.meta.url),"utf8");
test("public agent profiles are tenant-scoped and expose bounded display data",async()=>{const[site,page,view,appCss,publicCss,checklist,schema,migration,teamApi,mediaApi,publicMediaApi]=await Promise.all([read("../db/public-site.ts"),read("../app/site/[slug]/[section]/page.tsx"),read("../app/site/[slug]/public-website.tsx"),read("../app/globals.css"),read("../app/public-templates.css"),read("../docs/DELIVERY-CHECKLIST.md"),read("../db/schema.ts"),read("../drizzle/0027_agent_profiles.sql"),read("../app/api/team/invitations/route.ts"),read("../app/api/media/route.ts"),read("../app/api/public/[slug]/media/route.ts")]);
assert.match(site,/export type PublicAgent/);
assert.match(site,/function listPublicAgents|listPublicAgents/);
assert.match(site,/WHERE m\.agency_id=\?/);
assert.match(site,/p\.agency_id=m\.agency_id/);
assert.match(site,/p\.listing_agent_id=m\.user_id/);
assert.match(site,/p\.status='Available'/);
assert.match(site,/agent_profiles/);
assert.match(site,/photoMediaId/);
assert.match(site,/phone:string/);
assert.doesNotMatch(site,/SELECT \*/);
assert.match(page,/section === "agents" \? listPublicAgents\(agency\.id\)/);
assert.match(view,/function AgentGrid/);
assert.match(view,/agent\.listings/);
assert.match(view,/public-agent-photo/);
assert.match(view,/agent\.phone/);
assert.match(view,/agent\.experience/);
assert.match(view,/agent\.bio/);
assert.doesNotMatch(view,/agent\.email/);
assert.match(appCss,/team-profile/);
assert.match(view,/public-agent-grid/);
assert.match(publicCss,/public-agent-grid/);
assert.match(publicCss,/public-agent-photo/);
assert.match(schema,/agentProfiles=sqliteTable\("agent_profiles"/);
assert.match(migration,/CREATE TABLE `agent_profiles`/);
assert.match(teamApi,/PATCH/);
assert.match(teamApi,/profile_photo_media_id/);
assert.match(teamApi,/public_enabled/);
assert.match(teamApi,/team\.manage/);
assert.match(teamApi,/You can only edit your own public profile/);
const app=await read("../app/estara-app.tsx");
assert.match(app, /<Team notify=\{notify\} brand=\{brand\}/);
assert.match(app, /Preview agent page/);
assert.match(app, /`\$\{publicWebsiteHref\(brand\)\}\/agents`/);
assert.match(mediaApi,/agent_photo/);
assert.match(publicMediaApi,/m\.kind='agent_photo'/);
assert.match(checklist,/public agent profile/);
});
