import assert from"node:assert/strict";
import {readFile} from"node:fs/promises";
import test from"node:test";

const read=file=>readFile(new URL(file,import.meta.url),"utf8");

test("workspace properties can be edited, deleted and activated with exact readiness feedback",async()=>{
 const [ui,route,actions]=await Promise.all([read("../app/estara-app.tsx"),read("../app/api/workspace/route.ts"),read("../app/api/workspace/actions/route.ts")]);
 assert.match(route,/async function PATCH/);
 assert.match(route,/async function DELETE/);
 assert.match(route,/propertyCompleteness/);
 assert.match(route,/SELECT COUNT\(\*\) FROM media_assets m WHERE m\.agency_id=properties\.agency_id AND m\.property_id=properties\.id AND m\.kind='property_photo'/);
 assert.doesNotMatch(route,/photo_count AS photos/);
 assert.match(route,/prepareOwnerContact/);
 assert.match(route,/prepareMandateIfNeeded/);
 assert.match(route,/ownerStatement/);
 assert.match(route,/mandateStatement/);
 assert.match(route,/appendMandateWork/);
 assert.match(route,/renew_mandate/);
 assert.match(route,/mandate\.created/);
 assert.match(route,/prepareAudit/);
 assert.match(route,/prepareDomainEvent/);
 assert.match(route,/env\.DB\.batch\(statements\)/);
 assert.match(route,/UPDATE properties SET status='Withdrawn'/);
 assert.match(route,/invalidatePublicSite\(w\.agencyId,id\)/);
 assert.match(ui,/propertyToEdit/);
 assert.match(ui,/Edit details/);
 assert.match(ui,/Delete property/);
 assert.match(ui,/Complete details/);
 assert.match(ui,/propertyTypeOptions/);
 assert.match(ui,/needsLandSize/);
 assert.match(ui,/Monthly rent \(USD\)/);
 assert.match(ui,/Seller phone/);
 assert.match(ui,/Landlord phone/);
 assert.match(ui,/Publish listing/);
 assert.match(ui,/disabled=\{publishMissing\.length>0\}/);
 assert.match(ui,/Published-ready\. Improve later/);
 assert.doesNotMatch(ui,/required minLength=\{40\}/);
 assert.doesNotMatch(ui,/Street address<input required/);
 assert.match(ui,/mandateExpiresAt:property\?source\.mandateExpiresAt\|\|"":future\(\)/);
 assert.match(actions,/Add before publishing:/);
 assert.match(actions,/propertyPublishReadiness/);
 assert.match(actions,/propertyPhotoRequirement/);
 assert.match(actions,/autoVerified/);
});

test("property command mutations commit lifecycle evidence atomically and do not invent reactivation history",async()=>{
 const route=await read("../app/api/properties/[id]/route.ts");
 assert.match(route,/prepareAudit/);
 assert.match(route,/prepareDomainEvent/);
 assert.match(route,/canTransitionProperty\(fromStatus, "Available"\)/);
 assert.match(route,/const fromStatus = current\.property\.status, statusChanged = fromStatus !== "Available"/);
 assert.match(route,/if \(statusChanged\)[\s\S]*property_status_events/);
 assert.match(route,/guardedPropertyAudit/);
 assert.match(route,/guardedPropertyEvent/);
 assert.match(route,/mutation_token=\?/);
 assert.match(route,/WHERE EXISTS\(SELECT 1 FROM properties WHERE id=\? AND agency_id=\? AND mutation_token=\?\)/);
 assert.match(route,/await env\.DB\.batch\(statements\)/);
 assert.doesNotMatch(route,/writeAudit|publishDomainEvent/);
});
