import { env } from "cloudflare:workers";
import { getChatGPTUser } from "../../chatgpt-auth";
import { requireWorkspace } from "../../../db/workspace";
import { AuthorizationError, requirePermission, writeAudit } from "../../../db/authorization";
import { accessiblePropertyIds, requirePropertyBranchAccess } from "../../../db/access-scope";
import { allocateOldest, dueDate, leaseDates, managementFee, minor, rentPeriod } from "../../../db/property-management-policy";

const clean=(value:unknown,max=300)=>typeof value==="string"?value.trim().slice(0,max):"";
const id=()=>crypto.randomUUID();
const jsonError=(error:unknown,fallback:string)=>error instanceof AuthorizationError?Response.json({error:error.message},{status:403}):Response.json({error:error instanceof Error?error.message:fallback},{status:400});
type Workspace=Awaited<ReturnType<typeof requireWorkspace>>;

async function context(permission:"property_management.read"|"property_management.manage"){
 const user=await getChatGPTUser();if(!user)throw new AuthorizationError("Sign in is required.");
 const workspace=await requireWorkspace(user);await requirePermission(workspace,permission);return{user,workspace};
}
async function managed(workspace:Workspace,managedPropertyId:string){const row=await env.DB.prepare(`SELECT mp.id,mp.property_id propertyId,mp.landlord_contact_id landlordContactId,mp.management_fee_basis_points managementFeeBasisPoints,p.title,p.currency FROM managed_properties mp JOIN properties p ON p.id=mp.property_id AND p.agency_id=mp.agency_id WHERE mp.id=? AND mp.agency_id=?`).bind(managedPropertyId,workspace.agencyId).first<{id:string;propertyId:string;landlordContactId:string;managementFeeBasisPoints:number;title:string;currency:string}>();if(!row)throw new Error("Managed property was not found.");await requirePropertyBranchAccess(workspace,row.propertyId);return row}
async function lease(workspace:Workspace,leaseId:string){const row=await env.DB.prepare(`SELECT l.*,mp.property_id propertyId,mp.landlord_contact_id landlordContactId,mp.management_fee_basis_points managementFeeBasisPoints FROM leases l JOIN managed_properties mp ON mp.id=l.managed_property_id AND mp.agency_id=l.agency_id WHERE l.id=? AND l.agency_id=?`).bind(leaseId,workspace.agencyId).first<Record<string,any>>();if(!row)throw new Error("Lease was not found.");await requirePropertyBranchAccess(workspace,row.propertyId);return row}
async function addRole(agencyId:string,contactId:string,role:string){const contact=await env.DB.prepare("SELECT roles FROM contacts WHERE id=? AND agency_id=?").bind(contactId,agencyId).first<{roles:string}>();if(!contact)throw new Error("The contact is outside this agency.");let roles:string[]=[];try{roles=JSON.parse(contact.roles)}catch{}if(!roles.includes(role))await env.DB.prepare("UPDATE contacts SET roles=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND agency_id=?").bind(JSON.stringify([...roles,role]),contactId,agencyId).run()}

export async function GET(){try{const{workspace}=await context("property_management.read"),a=workspace.agencyId,scope=await accessiblePropertyIds(workspace),allowed=scope?[...scope]:null;
 const [properties,contacts,managedRows,leases,charges,payments,receipts,deposits,expenses,statements]=await Promise.all([
  env.DB.prepare("SELECT id,title,reference,currency,branch_id branchId FROM properties WHERE agency_id=? ORDER BY title").bind(a).all(),env.DB.prepare("SELECT id,full_name fullName,roles FROM contacts WHERE agency_id=? ORDER BY full_name").bind(a).all(),
  env.DB.prepare(`SELECT mp.id,mp.property_id propertyId,p.title property,mp.landlord_contact_id landlordContactId,c.full_name landlord,mp.management_fee_basis_points managementFeeBasisPoints,mp.starts_at startsAt,mp.status FROM managed_properties mp JOIN properties p ON p.id=mp.property_id AND p.agency_id=mp.agency_id JOIN contacts c ON c.id=mp.landlord_contact_id AND c.agency_id=mp.agency_id WHERE mp.agency_id=? ORDER BY p.title`).bind(a).all(),
  env.DB.prepare(`SELECT l.id,l.managed_property_id managedPropertyId,l.tenant_contact_id tenantContactId,c.full_name tenant,l.starts_at startsAt,l.ends_at endsAt,l.rent_minor rentMinor,l.deposit_minor depositMinor,l.currency,l.due_day dueDay,l.status,mp.property_id propertyId,p.title property FROM leases l JOIN managed_properties mp ON mp.id=l.managed_property_id AND mp.agency_id=l.agency_id JOIN properties p ON p.id=mp.property_id AND p.agency_id=l.agency_id JOIN contacts c ON c.id=l.tenant_contact_id AND c.agency_id=l.agency_id WHERE l.agency_id=? ORDER BY l.starts_at DESC`).bind(a).all(),
  env.DB.prepare(`SELECT rc.id,rc.lease_id leaseId,rc.period,rc.due_at dueAt,rc.amount_minor amountMinor,rc.allocated_minor allocatedMinor,CASE WHEN rc.allocated_minor>=rc.amount_minor THEN 'paid' WHEN rc.due_at<CURRENT_TIMESTAMP THEN 'overdue' ELSE rc.status END status,mp.property_id propertyId FROM rent_charges rc JOIN leases l ON l.id=rc.lease_id AND l.agency_id=rc.agency_id JOIN managed_properties mp ON mp.id=l.managed_property_id AND mp.agency_id=l.agency_id WHERE rc.agency_id=? ORDER BY rc.due_at DESC`).bind(a).all(),
  env.DB.prepare(`SELECT rp.id,rp.lease_id leaseId,rp.amount_minor amountMinor,rp.unallocated_minor unallocatedMinor,rp.currency,rp.method,rp.provider,rp.provider_reference providerReference,rp.received_at receivedAt,mp.property_id propertyId FROM rent_payments rp JOIN leases l ON l.id=rp.lease_id AND l.agency_id=rp.agency_id JOIN managed_properties mp ON mp.id=l.managed_property_id AND mp.agency_id=l.agency_id WHERE rp.agency_id=? ORDER BY rp.received_at DESC`).bind(a).all(),
  env.DB.prepare(`SELECT rr.id,rr.payment_id paymentId,rr.receipt_number receiptNumber,rr.amount_minor amountMinor,rr.currency,rr.issued_at issuedAt,mp.property_id propertyId FROM rent_receipts rr JOIN rent_payments rp ON rp.id=rr.payment_id AND rp.agency_id=rr.agency_id JOIN leases l ON l.id=rp.lease_id AND l.agency_id=rp.agency_id JOIN managed_properties mp ON mp.id=l.managed_property_id AND mp.agency_id=l.agency_id WHERE rr.agency_id=? ORDER BY rr.issued_at DESC`).bind(a).all(),env.DB.prepare(`SELECT td.id,td.lease_id leaseId,td.amount_minor amountMinor,td.currency,td.status,td.released_minor releasedMinor,td.deduction_minor deductionMinor,td.note,mp.property_id propertyId FROM tenancy_deposits td JOIN leases l ON l.id=td.lease_id AND l.agency_id=td.agency_id JOIN managed_properties mp ON mp.id=l.managed_property_id AND mp.agency_id=l.agency_id WHERE td.agency_id=? ORDER BY td.created_at DESC`).bind(a).all(),
  env.DB.prepare(`SELECT pe.id,pe.managed_property_id managedPropertyId,pe.category,pe.description,pe.amount_minor amountMinor,pe.currency,pe.incurred_at incurredAt,mp.property_id propertyId FROM property_expenses pe JOIN managed_properties mp ON mp.id=pe.managed_property_id AND mp.agency_id=pe.agency_id WHERE pe.agency_id=? ORDER BY pe.incurred_at DESC`).bind(a).all(),env.DB.prepare("SELECT id,landlord_contact_id landlordContactId,period_start periodStart,period_end periodEnd,currency,rent_collected_minor rentCollectedMinor,management_fee_minor managementFeeMinor,expenses_minor expensesMinor,net_payable_minor netPayableMinor,status,finalized_at finalizedAt FROM landlord_statements WHERE agency_id=? ORDER BY finalized_at DESC").bind(a).all()
 ]);const filter=(rows:any[],key="propertyId")=>allowed?rows.filter(row=>allowed.includes(row[key])):rows;
 return Response.json({properties:filter(properties.results as any[],"id"),contacts:contacts.results,managedProperties:filter(managedRows.results as any[]),leases:filter(leases.results as any[]),charges:filter(charges.results as any[]),payments:filter(payments.results as any[]),receipts:filter(receipts.results as any[]),deposits:filter(deposits.results as any[]),expenses:filter(expenses.results as any[]),statements:allowed?[]:statements.results});
 }catch(error){return jsonError(error,"Property management could not be loaded.")}}

export async function POST(request:Request){try{const{user,workspace}=await context("property_management.manage"),a=workspace.agencyId,body=await request.json(),action=clean(body.action,40);
 if(action==="create_management"){const propertyId=clean(body.propertyId,100),landlordContactId=clean(body.landlordContactId,100),fee=Math.round(Number(body.feePercent)*100),startsAt=new Date(clean(body.startsAt,40));if(!propertyId||!landlordContactId||!Number.isInteger(fee)||fee<0||fee>10000||!Number.isFinite(startsAt.getTime()))throw new Error("Property, landlord, start date and a valid fee are required.");await requirePropertyBranchAccess(workspace,propertyId);await addRole(a,landlordContactId,"landlord");const recordId=id();await env.DB.prepare("INSERT INTO managed_properties(id,agency_id,property_id,landlord_contact_id,management_fee_basis_points,starts_at,created_by) VALUES(?,?,?,?,?,?,?)").bind(recordId,a,propertyId,landlordContactId,fee,startsAt.toISOString(),user.userId).run();await writeAudit(workspace,"managed_property.created","managed_property",recordId,{propertyId,landlordContactId});return Response.json({id:recordId},{status:201})}
 if(action==="create_lease"){const managedPropertyId=clean(body.managedPropertyId,100),tenantContactId=clean(body.tenantContactId,100),dates=leaseDates(body.startsAt,body.endsAt),rent=minor(body.rent),deposit=Number(body.deposit||0)>0?minor(body.deposit):0,dueDay=Math.round(Number(body.dueDay||1)),property=await managed(workspace,managedPropertyId);if(!tenantContactId||dueDay<1||dueDay>31)throw new Error("Tenant and a valid due day are required.");await addRole(a,tenantContactId,"tenant");const overlap=await env.DB.prepare("SELECT id FROM leases WHERE agency_id=? AND managed_property_id=? AND status IN ('draft','active') AND starts_at<? AND ends_at>? LIMIT 1").bind(a,managedPropertyId,dates.endsAt,dates.startsAt).first();if(overlap)throw new Error("This property already has an overlapping lease.");const leaseId=id(),statements=[env.DB.prepare("INSERT INTO leases(id,agency_id,managed_property_id,tenant_contact_id,starts_at,ends_at,rent_minor,deposit_minor,currency,due_day,status,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,'active',?)").bind(leaseId,a,managedPropertyId,tenantContactId,dates.startsAt,dates.endsAt,rent,deposit,clean(body.currency,3)||property.currency,dueDay,user.userId)];if(deposit)statements.push(env.DB.prepare("INSERT INTO tenancy_deposits(id,agency_id,lease_id,amount_minor,currency,status,note) VALUES(?,?,?,?,?,'expected','Awaiting receipt')").bind(id(),a,leaseId,deposit,clean(body.currency,3)||property.currency));await env.DB.batch(statements);await writeAudit(workspace,"lease.activated","lease",leaseId,{managedPropertyId,tenantContactId});return Response.json({id:leaseId},{status:201})}
 if(action==="generate_rent"){const leaseId=clean(body.leaseId,100),period=rentPeriod(body.period),record=await lease(workspace,leaseId);if(record.status!=="active")throw new Error("Only an active lease can be charged.");const chargeId=id();await env.DB.prepare("INSERT INTO rent_charges(id,agency_id,lease_id,period,due_at,amount_minor,status) VALUES(?,?,?,?,?,?,'due')").bind(chargeId,a,leaseId,period,dueDate(period,record.due_day),record.rent_minor).run();await writeAudit(workspace,"rent.charge_created","rent_charge",chargeId,{leaseId,period});return Response.json({id:chargeId},{status:201})}
 if(action==="record_payment"){const leaseId=clean(body.leaseId,100),amount=minor(body.amount),record=await lease(workspace,leaseId),method=clean(body.method,30),provider=clean(body.provider,60),providerReference=clean(body.providerReference,120),received=new Date(clean(body.receivedAt,40)||Date.now());if(!method||!Number.isFinite(received.getTime()))throw new Error("Payment method and receipt date are required.");if(providerReference&&!provider)throw new Error("Choose a provider for the provider reference.");const charges=await env.DB.prepare("SELECT id,amount_minor amountMinor,allocated_minor allocatedMinor FROM rent_charges WHERE agency_id=? AND lease_id=? AND allocated_minor<amount_minor ORDER BY due_at,id").bind(a,leaseId).all<{id:string;amountMinor:number;allocatedMinor:number}>(),allocation=allocateOldest(amount,charges.results),paymentId=id(),receiptId=id(),receiptNumber=`EST-RCPT-${new Date().toISOString().slice(0,10).replaceAll("-","")}-${paymentId.slice(0,8).toUpperCase()}`,statements:any[]=[env.DB.prepare("INSERT INTO rent_payments(id,agency_id,lease_id,payer_contact_id,amount_minor,unallocated_minor,currency,method,provider,provider_reference,received_at,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)").bind(paymentId,a,leaseId,record.tenant_contact_id,amount,allocation.unallocatedMinor,record.currency,method,provider||null,providerReference||null,received.toISOString(),user.userId),env.DB.prepare("INSERT INTO rent_receipts(id,agency_id,payment_id,receipt_number,amount_minor,currency,issued_by) VALUES(?,?,?,?,?,?,?)").bind(receiptId,a,paymentId,receiptNumber,amount,record.currency,user.userId)];for(const item of allocation.allocations){statements.push(env.DB.prepare("INSERT INTO payment_allocations(id,agency_id,payment_id,charge_id,amount_minor) VALUES(?,?,?,?,?)").bind(id(),a,paymentId,item.chargeId,item.amountMinor));statements.push(env.DB.prepare("UPDATE rent_charges SET allocated_minor=allocated_minor+?,status=CASE WHEN allocated_minor+?>=amount_minor THEN 'paid' ELSE 'part_paid' END,updated_at=CURRENT_TIMESTAMP WHERE id=? AND agency_id=?").bind(item.amountMinor,item.amountMinor,item.chargeId,a))}await env.DB.batch(statements);await writeAudit(workspace,"rent.payment_recorded","rent_payment",paymentId,{leaseId,amount,receiptNumber,unallocatedMinor:allocation.unallocatedMinor});return Response.json({id:paymentId,receiptNumber,allocations:allocation.allocations,unallocatedMinor:allocation.unallocatedMinor},{status:201})}
 if(action==="hold_deposit"){const leaseId=clean(body.leaseId,100),amount=minor(body.amount),record=await lease(workspace,leaseId),paymentId=clean(body.paymentId,100);if(paymentId&&!await env.DB.prepare("SELECT 1 FROM rent_payments WHERE id=? AND agency_id=? AND lease_id=?").bind(paymentId,a,leaseId).first())throw new Error("Deposit payment was not found.");const existing=await env.DB.prepare("SELECT id FROM tenancy_deposits WHERE agency_id=? AND lease_id=? LIMIT 1").bind(a,leaseId).first<{id:string}>(),depositId=existing?.id||id();if(existing)await env.DB.prepare("UPDATE tenancy_deposits SET amount_minor=?,currency=?,status='held',received_payment_id=?,note=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND agency_id=?").bind(amount,record.currency,paymentId||null,clean(body.note,500),depositId,a).run();else await env.DB.prepare("INSERT INTO tenancy_deposits(id,agency_id,lease_id,amount_minor,currency,status,received_payment_id,note) VALUES(?,?,?,?,?,'held',?,?)").bind(depositId,a,leaseId,amount,record.currency,paymentId||null,clean(body.note,500)).run();await writeAudit(workspace,"deposit.held","tenancy_deposit",depositId,{leaseId,amount});return Response.json({id:depositId},{status:201})}
 if(action==="record_expense"){const managedPropertyId=clean(body.managedPropertyId,100),property=await managed(workspace,managedPropertyId),amount=minor(body.amount),category=clean(body.category,60),description=clean(body.description,500),incurred=new Date(clean(body.incurredAt,40));if(!category||!description||!Number.isFinite(incurred.getTime()))throw new Error("Category, description and date are required.");const expenseId=id();await env.DB.prepare("INSERT INTO property_expenses(id,agency_id,managed_property_id,landlord_contact_id,category,description,amount_minor,currency,incurred_at,created_by) VALUES(?,?,?,?,?,?,?,?,?,?)").bind(expenseId,a,managedPropertyId,property.landlordContactId,category,description,amount,property.currency,incurred.toISOString(),user.userId).run();await writeAudit(workspace,"property_expense.recorded","property_expense",expenseId,{managedPropertyId,amount});return Response.json({id:expenseId},{status:201})}
 if(action==="process_arrears"){const scoped=await accessiblePropertyIds(workspace),rows=await env.DB.prepare(`SELECT rc.id,rc.lease_id leaseId,mp.property_id propertyId,l.tenant_contact_id tenantContactId FROM rent_charges rc JOIN leases l ON l.id=rc.lease_id AND l.agency_id=rc.agency_id JOIN managed_properties mp ON mp.id=l.managed_property_id AND mp.agency_id=l.agency_id WHERE rc.agency_id=? AND rc.due_at<CURRENT_TIMESTAMP AND rc.allocated_minor<rc.amount_minor AND rc.status!='overdue'`).bind(a).all<any>(),due=scoped?rows.results.filter(row=>scoped.has(row.propertyId)):rows.results,statements:any[]=[];for(const row of due){statements.push(env.DB.prepare("UPDATE rent_charges SET status='overdue',updated_at=CURRENT_TIMESTAMP WHERE id=? AND agency_id=?").bind(row.id,a));statements.push(env.DB.prepare("INSERT INTO next_actions(id,agency_id,resource_type,resource_id,action_type,reason,priority,due_at,status,assigned_user_id) VALUES(?,?,'rent_charge',?,'arrears_follow_up','Contact tenant about overdue rent','high',CURRENT_TIMESTAMP,'open',?)").bind(id(),a,row.id,user.userId))}if(statements.length)await env.DB.batch(statements);await writeAudit(workspace,"arrears.processed","rent_charge","batch",{count:due.length});return Response.json({processed:due.length})}
 if(action==="finalize_statement"){const landlordContactId=clean(body.landlordContactId,100),periodStart=new Date(clean(body.periodStart,40)),periodEnd=new Date(clean(body.periodEnd,40));if(!landlordContactId||!Number.isFinite(periodStart.getTime())||!Number.isFinite(periodEnd.getTime())||periodEnd<=periodStart)throw new Error("Landlord and a valid statement period are required.");await addRole(a,landlordContactId,"landlord");const rentRows=await env.DB.prepare(`SELECT pa.amount_minor amountMinor,mp.management_fee_basis_points feeBasisPoints,mp.property_id propertyId,p.title FROM payment_allocations pa JOIN rent_payments rp ON rp.id=pa.payment_id AND rp.agency_id=pa.agency_id JOIN leases l ON l.id=rp.lease_id AND l.agency_id=rp.agency_id JOIN managed_properties mp ON mp.id=l.managed_property_id AND mp.agency_id=l.agency_id JOIN properties p ON p.id=mp.property_id AND p.agency_id=mp.agency_id WHERE pa.agency_id=? AND mp.landlord_contact_id=? AND rp.received_at>=? AND rp.received_at<?`).bind(a,landlordContactId,periodStart.toISOString(),periodEnd.toISOString()).all<any>(),expenseRows=await env.DB.prepare("SELECT amount_minor amountMinor,description,managed_property_id managedPropertyId FROM property_expenses WHERE agency_id=? AND landlord_contact_id=? AND incurred_at>=? AND incurred_at<? AND status='approved'").bind(a,landlordContactId,periodStart.toISOString(),periodEnd.toISOString()).all<any>();for(const row of rentRows.results)await requirePropertyBranchAccess(workspace,row.propertyId);const rentCollected=rentRows.results.reduce((sum,row)=>sum+row.amountMinor,0),fees=rentRows.results.reduce((sum,row)=>sum+managementFee(row.amountMinor,row.feeBasisPoints),0),expenses=expenseRows.results.reduce((sum,row)=>sum+row.amountMinor,0),statementId=id(),currency="USD",snapshot=JSON.stringify({version:1,rent:rentRows.results,expenses:expenseRows.results,generatedAt:new Date().toISOString()});await env.DB.prepare("INSERT INTO landlord_statements(id,agency_id,landlord_contact_id,period_start,period_end,currency,rent_collected_minor,management_fee_minor,expenses_minor,net_payable_minor,snapshot,status,finalized_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,'final',?)").bind(statementId,a,landlordContactId,periodStart.toISOString(),periodEnd.toISOString(),currency,rentCollected,fees,expenses,rentCollected-fees-expenses,snapshot,user.userId).run();await writeAudit(workspace,"landlord_statement.finalized","landlord_statement",statementId,{landlordContactId,rentCollected,fees,expenses});return Response.json({id:statementId,netPayableMinor:rentCollected-fees-expenses},{status:201})}
 return Response.json({error:"Unknown property-management action."},{status:400});
 }catch(error){return jsonError(error,"Property-management operation failed.")}}
