"use client";
import {FormEvent,useMemo,useState} from "react";
type View="today"|"properties"|"enquiries"|"marketing"|"seller";
type Property={id:number;title:string;location:string;price:string;beds:number;baths:number;status:"Draft"|"Available";ref:string;photos:number;owner:string;size:string};
const seed:Property[]=[
{id:1,title:"Garden sanctuary in Greendale",location:"Greendale, Harare",price:"US$180,000",beds:4,baths:3,status:"Available",ref:"EST-2401",photos:18,owner:"+263 77 234 9810",size:"2,100 m²"},
{id:2,title:"Modern family home",location:"Borrowdale, Harare",price:"US$320,000",beds:5,baths:4,status:"Available",ref:"EST-2398",photos:14,owner:"+263 71 990 2221",size:"3,400 m²"},
{id:3,title:"Sunlit townhouse",location:"Newlands, Harare",price:"US$1,450 / month",beds:3,baths:2,status:"Draft",ref:"EST-2410",photos:5,owner:"",size:""}];
const nav:[View,string,string][]=[["today","Today","⌂"],["properties","Properties","◇"],["enquiries","Enquiries","↗"],["marketing","Marketing","✦"],["seller","Seller portal","◉"]];
const complete=(p:Property)=>Math.round([p.title,p.location,p.price,p.beds,p.baths,p.photos>=8,p.owner,p.size].filter(Boolean).length/8*100);
export default function EstaraApp(){
 const [view,setView]=useState<View>("today"),[properties,setProperties]=useState(seed),[selected,setSelected]=useState(seed[0]),[capture,setCapture]=useState(false),[toast,setToast]=useState("");
 const [leads,setLeads]=useState([{name:"Tariro Moyo",property:"Garden sanctuary",time:"12 min",status:"New",initials:"TM"},{name:"Daniel Ncube",property:"Modern family home",time:"44 min",status:"Waiting",initials:"DN"},{name:"Nyasha Dube",property:"Sunlit townhouse",time:"Yesterday",status:"Contacted",initials:"ND"}]);
 const notify=(m:string)=>{setToast(m);setTimeout(()=>setToast(""),2400)}; const contact=(i:number)=>{setLeads(x=>x.map((r,n)=>n===i?{...r,status:"Contacted"}:r));notify("Contact recorded. Follow-up set for tomorrow.")};
 const activate=(p:Property)=>{const next={...p,status:"Available" as const};setProperties(x=>x.map(r=>r.id===p.id?next:r));setSelected(next);notify("Property activated across website and marketing.")};
 return <div className="shell"><aside><div className="brand"><i>E</i><span>ESTARA<small>HouseLink</small></span></div><div className="agency"><b>PP</b><span><strong>Prime Property</strong><small>Harare office</small></span><em>⌄</em></div><nav>{nav.map(n=><button className={view===n[0]?"active":""} onClick={()=>setView(n[0])} key={n[0]}><i>{n[2]}</i>{n[1]}{n[0]==="enquiries"&&<b>3</b>}</button>)}</nav><div className="user"><b>SN</b><span><strong>Sarah Ncube</strong><small>Principal</small></span><em>•••</em></div></aside><main><header><button className="mobile-logo" onClick={()=>setView("today")}>E <b>ESTARA</b></button><button className="search" onClick={()=>notify("Search by property, client or phone number")}>⌕ <span>Search anything…</span><kbd>⌘ K</kbd></button><div><button onClick={()=>notify("Low data mode enabled")}>↓</button><button onClick={()=>notify("You’re all caught up")}>♢</button><button className="primary" onClick={()=>setCapture(true)}>＋ Add property</button></div></header>
 {view==="today"&&<Today properties={properties} leads={leads} go={setView} pick={(p:Property)=>{setSelected(p);setView("properties")}} add={()=>setCapture(true)} contact={contact}/>} 
 {view==="properties"&&<Properties rows={properties} selected={selected} pick={setSelected} add={()=>setCapture(true)} activate={activate} notify={notify}/>} 
 {view==="enquiries"&&<Enquiries rows={leads} contact={contact}/>} 
 {view==="marketing"&&<Marketing property={selected} notify={notify}/>} 
 {view==="seller"&&<Seller property={selected}/>} 
 <nav className="mobile-nav">{nav.slice(0,4).map(n=><button className={view===n[0]?"active":""} onClick={()=>setView(n[0])} key={n[0]}><i>{n[2]}</i>{n[1]}</button>)}</nav><button className="fab" onClick={()=>setCapture(true)}>＋</button></main>{capture&&<Capture close={()=>setCapture(false)} save={(p:Property)=>{setProperties(x=>[...x,p]);setSelected(p);setCapture(false);setView("properties");notify("Draft saved. Continue whenever you’re ready.")}}/>}{toast&&<div className="toast">✓ {toast}</div>}</div>
}
function Heading({label,title,text,action}:{label:string;title:string;text:string;action?:React.ReactNode}){return <div className="heading"><div><span className="eyebrow">{label}</span><h1>{title}</h1><p>{text}</p></div>{action}</div>}
function Today({properties,leads,go,pick,add,contact}:any){const stats=[["↗","3","New enquiries","Since yesterday","coral","enquiries"],["⌕","6","Follow-ups due","2 are overdue","amber","enquiries"],["□","4","Viewings today","Next at 11:30","blue","seller"],["$","2","Offers to review","US$482k total","green","properties"]];return <div className="page"><Heading label="TUESDAY, 18 AUGUST" title="Good morning, Sarah." text="Here’s where your business needs you today." action={<button className="outline" onClick={add}>＋ Quick add</button>}/><section className="money"><div className="section-head"><div><h2>Today’s business</h2><p>Stay ahead of the work that protects your revenue.</p></div><span className="live"><i/> Live</span></div><div className="stats">{stats.map(s=><button className={`stat ${s[4]}`} onClick={()=>go(s[5])} key={s[2]}><i>{s[0]}</i><strong>{s[1]}</strong><b>{s[2]}</b><small>{s[3]} <em>→</em></small></button>)}</div></section><div className="columns"><section className="panel attention"><div className="panel-head"><div><h2>Needs your attention</h2><p>Act now to keep opportunities moving.</p></div><button onClick={()=>go("enquiries")}>View all</button></div><button onClick={()=>contact(1)}><i className="red">!</i><span><strong>Potential client waiting</strong><p>Daniel enquired about Borrowdale.</p><small>44 minutes ago</small></span><b>Contact now</b></button><button onClick={()=>pick(properties[2])}><i className="amber">◇</i><span><strong>Listing is 63% complete</strong><p>Sunlit townhouse needs key details.</p><small>Draft property</small></span><b>Complete listing</b></button><button onClick={()=>go("seller")}><i className="blue">▤</i><span><strong>Seller report is ready</strong><p>Greendale weekly activity report.</p><small>Ready for review</small></span><b>Review report</b></button></section><section className="panel schedule"><div className="panel-head"><div><h2>Today’s schedule</h2><p>4 viewings booked</p></div><button>Full calendar</button></div>{[["09:00","Greendale garden sanctuary","Tariro Moyo"],["11:30","Borrowdale family home","Peter Zhou"],["14:00","Highlands apartment","Rutendo Sango"]].map((x,i)=><div className={i===1?"next":""} key={x[0]}><time>{x[0]}<small>{i<2?"AM":"PM"}</small></time><i/><span><strong>{x[1]}</strong><small>with {x[2]}</small></span><b>{i===1?"Next":i===0?"Complete":"Confirmed"}</b></div>)}</section></div><section className="panel pulse"><div className="panel-head"><div><h2>Property pulse</h2><p>2 active listings are working for you.</p></div><button onClick={()=>go("properties")}>All properties →</button></div><div className="cards">{properties.map((p:Property,i:number)=><button onClick={()=>pick(p)} key={p.id}><div className={`photo photo-${i}`}><span>{p.status}</span><b>{p.photos} photos</b></div><article><small>{p.ref}</small><strong>{p.title}</strong><p>{p.location}</p><div><b>{p.price}</b><span>{p.beds} beds · {p.baths} baths</span></div></article></button>)}</div></section></div>}
function Properties({rows,selected,pick,add,activate,notify}:any){const pct=complete(selected);return <div className="page"><Heading label="PORTFOLIO" title="Properties" text="Capture once. Market everywhere." action={<button className="primary" onClick={add}>＋ Add property</button>}/><div className="property-work"><section className="panel property-list"><div className="panel-head"><h2>{rows.length} properties</h2><span>2 available · 1 draft</span></div>{rows.map((p:Property,i:number)=><button className={p.id===selected.id?"selected":""} onClick={()=>pick(p)} key={p.id}><i className={`thumb photo-${i}`}/><span><small>{p.ref} · {p.status}</small><strong>{p.title}</strong><p>{p.location}</p><b>{p.price}</b></span><em>›</em></button>)}</section><section className="panel detail"><div className="detail-hero"><span>{selected.status}</span><div><small>{selected.ref}</small><h2>{selected.title}</h2><p>{selected.location}</p></div></div><article><div className="price"><strong>{selected.price}</strong><span>{selected.beds} bedrooms · {selected.baths} bathrooms · {selected.size||"Size needed"}</span></div><div className="complete"><div><strong>Listing completeness</strong><b>{pct}%</b></div><span><i style={{width:`${pct}%`}}/></span>{pct<100&&<p>⚠ Add {!selected.size?"stand size, ":""}{!selected.owner?"owner phone, ":""}{selected.photos<8?"more photos":"final details"}.</p>}</div><div className="chips"><span>Borehole</span><span>Solar</span><span>Walled</span><span>Garden</span></div><div className="actions">{selected.status==="Draft"?<button className="primary" disabled={pct<75} onClick={()=>activate(selected)}>✦ Activate property</button>:<button className="whatsapp" onClick={()=>notify("WhatsApp message copied and ready to share")}>Share on WhatsApp</button>}<button className="outline" onClick={()=>window.print()}>Print brochure</button></div></article></section></div></div>}
function Enquiries({rows,contact}:any){return <div className="page"><Heading label="CONVERSION" title="Enquiries" text="Every opportunity has an owner and a next step." action={<button className="primary">＋ Record enquiry</button>}/><section className="panel enquiry"><div className="tabs"><button className="active">All enquiries <b>3</b></button><button>New</button><button>Contacted</button><button>Viewing</button></div>{rows.map((r:any,i:number)=><div className="lead" key={r.name}><i>{r.initials}</i><span><strong>{r.name}</strong><p>{r.property}</p></span><em className={r.status.toLowerCase()}>{r.status}</em><small>{r.time}</small><button disabled={r.status==="Contacted"} onClick={()=>contact(i)}>{r.status==="Contacted"?"Follow-up set":"Contact now"}</button></div>)}</section></div>}
function Marketing({property,notify}:any){const [format,setFormat]=useState("WhatsApp card");return <div className="page"><Heading label="MARKET FASTER" title="Marketing studio" text="One property. Every channel. Always on brand."/><div className="market"><section className="panel formats"><h2>Choose a format</h2>{["WhatsApp card","Instagram post","Instagram story","Facebook creative","PDF brochure","Social caption"].map(x=><button className={format===x?"active":""} onClick={()=>setFormat(x)} key={x}><i>✦</i>{x}<b>›</b></button>)}</section><section className="creative"><div className="art"><b>PRIME PROPERTY</b><div><small>FOR SALE · GREENDALE</small><h2>{property.title}</h2><p>{property.beds} bedrooms · {property.baths} bathrooms · Borehole · Solar</p><strong>{property.price}</strong></div></div><footer><span><strong>{format}</strong><small>Ready in agency branding</small></span><button className="outline" onClick={()=>notify(`${format} downloaded`)}>Download</button><button className="primary" onClick={()=>notify(`${format} ready to share`)}>Share</button></footer></section></div></div>}
function Seller({property}:any){return <div className="page seller"><div className="portal"><b>PP</b><span><strong>Prime Property</strong><small>Seller update centre</small></span><button>Contact Sarah</button></div><div className="seller-hero"><span className="eyebrow">YOUR PROPERTY</span><h1>{property.title}</h1><p>{property.location} · Listed by Sarah Ncube</p><div>{[["24","Days listed"],["846","Property views"],["18","Enquiries"],["6","Viewings"]].map(x=><span key={x[1]}><strong>{x[0]}</strong><small>{x[1]}</small></span>)}</div></div><div className="columns"><section className="panel report"><div className="panel-head"><div><h2>Weekly update</h2><p>11–18 August 2026</p></div><em>Strong interest</em></div><h3>Your property is gaining momentum.</h3><p>This week brought 214 new views, five enquiries and two completed viewings. Buyer feedback is positive about the garden, solar installation and presentation.</p><div><strong>Recommended next action</strong><p>Continue the current campaign and follow up with the two most interested viewers.</p></div></section><section className="panel activity"><h2>Recent activity</h2>{[["Today","New viewing booked","Peter Zhou · Friday 11:30"],["Yesterday","Buyer feedback received","Very interested"],["14 Aug","WhatsApp campaign shared","128 link visits"]].map(x=><div key={x[1]}><time>{x[0]}</time><i/><span><strong>{x[1]}</strong><small>{x[2]}</small></span></div>)}</section></div></div>}
function Capture({close,save}:any){const [f,setF]=useState({title:"",location:"",price:"",beds:"",baths:"",size:"",owner:"",photos:"0"});const p:Property={id:Date.now(),title:f.title||"Untitled property",location:f.location||"Location needed",price:f.price?`US$${Number(f.price).toLocaleString()}`:"Price needed",beds:+f.beds,baths:+f.baths,status:"Draft",ref:`EST-${Math.floor(2400+Math.random()*99)}`,photos:+f.photos,owner:f.owner,size:f.size};const submit=(e:FormEvent)=>{e.preventDefault();save(p)};return <div className="backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><form className="modal" onSubmit={submit}><header><div><span className="eyebrow">MOBILE CAPTURE</span><h2>Capture property</h2><p>Save now. Complete it as you go.</p></div><button type="button" onClick={close}>×</button></header><div className="capture-progress"><div><strong>Listing completeness</strong><b>{complete(p)}%</b></div><span><i style={{width:`${complete(p)}%`}}/></span></div><div className="form"><label className="wide">Property title<input required value={f.title} onChange={e=>setF({...f,title:e.target.value})} placeholder="Garden sanctuary in Greendale"/></label><label>Suburb & city<input required value={f.location} onChange={e=>setF({...f,location:e.target.value})} placeholder="Greendale, Harare"/></label><label>Price (USD)<input required type="number" value={f.price} onChange={e=>setF({...f,price:e.target.value})} placeholder="180000"/></label><label>Bedrooms<input type="number" value={f.beds} onChange={e=>setF({...f,beds:e.target.value})}/></label><label>Bathrooms<input type="number" value={f.baths} onChange={e=>setF({...f,baths:e.target.value})}/></label><label>Stand size<input value={f.size} onChange={e=>setF({...f,size:e.target.value})} placeholder="2,100 m²"/></label><label>Owner phone<input value={f.owner} onChange={e=>setF({...f,owner:e.target.value})} placeholder="+263 77 000 0000"/></label><label className="wide range">Property photos<input type="range" min="0" max="20" value={f.photos} onChange={e=>setF({...f,photos:e.target.value})}/><span>{f.photos} photos added</span><small>Move the slider to simulate phone uploads.</small></label></div><footer><button type="button" className="outline" onClick={close}>Cancel</button><button className="primary">Save draft</button></footer></form></div>}
