import Link from "next/link";
import { headers } from "next/headers";
import { notFound } from "next/navigation";
import { getPlatformIdentity } from "../db/platform-settings";

const capabilities=[
  {number:"01",title:"Capture property once",text:"Structured property records, mobile photo upload and listing readiness in one guided workflow."},
  {number:"02",title:"Never lose the next action",text:"Every enquiry, viewing and follow-up stays assigned, timed and visible to the right person."},
  {number:"03",title:"Market with confidence",text:"Agency-branded websites, property pages and channel-ready creative built from verified facts."},
  {number:"04",title:"Keep sellers informed",text:"Secure property-level access and reviewed reports powered by live, measurable activity."},
];
const flow=["Add your agency","Capture a property","Publish everywhere","Respond on time","Report with evidence"];

function normalizeHost(host:string){return host.toLowerCase().replace(/:\d+$/,"").replace(/\.$/,"")}
function isPlatformHost(host:string,platform:{domain:string;tenantDomainSuffix:string}){const domain=normalizeHost(host);return !domain||domain==="localhost"||domain==="127.0.0.1"||domain==="::1"||domain===normalizeHost(platform.domain)||domain===normalizeHost(platform.tenantDomainSuffix)}

export default async function Home(){const platform=await getPlatformIdentity(),requestHeaders=await headers(),host=requestHeaders.get("x-forwarded-host")||requestHeaders.get("host")||"";if(!isPlatformHost(host,platform)){const[{getPublicAgencyByHost,listPublicProperties},{PublicHome}]=await Promise.all([import("../db/public-site"),import("./site/[slug]/public-website")]),agency=await getPublicAgencyByHost(host,platform.tenantDomainSuffix);if(agency){const properties=await listPublicProperties(agency.id);return <PublicHome agency={agency} properties={properties}/>}notFound()}const initial=platform.shortName.slice(0,1),parent=platform.parentBrand?`A ${platform.parentBrand} product`:platform.descriptor,taglineParts=platform.tagline.split(".").map(x=>x.trim()).filter(Boolean),heroLead=(taglineParts[0]||"Your real estate business").replace("Real Estate Business","real estate business"),heroEm=taglineParts.slice(1).join(". ")||"Running smarter";return <main className="estara-landing">
  <nav className="landing-nav"><Link href="/" className="landing-logo"><i>{initial}</i><span>{platform.shortName}<small>{parent}</small></span></Link><div><a href="#platform">Platform</a><a href="#workflow">How it works</a><a href="#built-for">Built for Africa</a></div><Link className="landing-signin" href="/workspace">Open workspace <b>↗</b></Link></nav>
  <section className="landing-hero"><div className="landing-hero-copy"><span className="landing-eyebrow"><i/> ZIMBABWE-FIRST REAL ESTATE OS</span><h1>{heroLead}.<em>{heroEm}.</em></h1><p>{platform.platformName} brings properties, clients, follow-ups, viewings, marketing, agency websites and seller reporting into one calm, connected operating system.</p><div className="landing-hero-actions"><Link href="/workspace">Enter your workspace <b>→</b></Link><a href="#workflow">See the full workflow</a></div><footer><div><strong>One source of truth</strong><small>From first capture to seller report</small></div><div><strong>Built for accountability</strong><small>Clear ownership, deadlines and audit history</small></div></footer></div>
  <div className="landing-product-stage"><div className="landing-orbit orbit-one"/><div className="landing-orbit orbit-two"/><section className="landing-window"><header><div><i>{initial}</i><span>{platform.shortName}<small>Prime Property</small></span></div><button>＋ Add property</button></header><aside>{["Today","Properties","Enquiries","Marketing","Seller centre"].map((item,index)=><span className={index===0?"active":""} key={item}><i>{["⌂","◇","◎","✦","◌"][index]}</i>{item}</span>)}</aside><article><span className="landing-demo-label">GOOD MORNING, SARAH</span><h2>Everything that needs attention, today.</h2><div className="landing-kpis"><div><small>NEW ENQUIRIES</small><strong>12</strong><em>4 need a response</em></div><div><small>NEXT ACTIONS</small><strong>8</strong><em>2 overdue</em></div><div><small>VIEWINGS</small><strong>5</strong><em>Next at 11:30</em></div></div><section className="landing-focus"><header><strong>Priority follow-ups</strong><span>Live workspace</span></header>{[["TM","Tariro Moyo","Garden sanctuary","Respond · 8 min"],["DN","Daniel Ncube","Modern family home","Viewing · 11:30"],["NZ","N. Zhou","Sunlit townhouse","Follow up · Today"]].map(row=><div key={row[1]}><b>{row[0]}</b><span><strong>{row[1]}</strong><small>{row[2]}</small></span><em>{row[3]}</em></div>)}</section></article></section><div className="landing-float float-one"><i>✓</i><span><strong>Seller report approved</strong><small>Built from verified activity</small></span></div><div className="landing-float float-two"><i>↗</i><span><strong>Property is live</strong><small>Website and marketing ready</small></span></div></div></section>
  <section className="landing-proof"><span>ONE CONNECTED SYSTEM FOR</span><div>{["Independent agencies","Multi-agent teams","Property sellers","Rental portfolios","Diaspora owners"].map(item=><strong key={item}>{item}</strong>)}</div></section>
  <section className="landing-capabilities" id="platform"><header><div><span className="landing-eyebrow"><i/> THE OPERATING LAYER</span><h2>Less chasing.<br/><em>More moving.</em></h2></div><p>{platform.platformName} turns daily real estate work into a visible system—so the whole agency knows what happened, what matters now and what must happen next.</p></header><div className="landing-cap-grid">{capabilities.map(item=><article key={item.number}><span>{item.number}</span><i>↗</i><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></section>
  <section className="landing-workflow" id="workflow"><div><span className="landing-eyebrow"><i/> ONE CONTINUOUS WORKFLOW</span><h2>From a property name to a professional operating rhythm.</h2><p>Every step feeds the next. No double capture. No disconnected spreadsheets. No activity disappearing into private chats.</p><Link href="/workspace">Start inside {platform.shortName} <b>→</b></Link></div><ol>{flow.map((item,index)=><li key={item}><span>0{index+1}</span><strong>{item}</strong><i>{index<flow.length-1?"↓":"✓"}</i></li>)}</ol></section>
  <section className="landing-africa" id="built-for"><div><span className="landing-eyebrow"><i/> BUILT FROM THE MARKET OUTWARD</span><h2>Global-grade software.<br/><em>Grounded in how Africa moves.</em></h2><p>Mobile-first property work, WhatsApp-ready communication, low-data thinking, diaspora visibility and practical agency accountability—designed into the operating model.</p><div>{["Mobile-led","WhatsApp-ready","USD-aware","Diaspora-friendly"].map(item=><span key={item}>✓ {item}</span>)}</div></div><aside><span>ZW</span><div><strong>Zimbabwe first.</strong><p>Designed to expand across African property markets without losing local relevance.</p></div></aside></section>
  <section className="landing-final"><span>YOUR NEXT PROPERTY DESERVES A BETTER SYSTEM</span><h2>Run the agency your ambition requires.</h2><p>One workspace. Clear ownership. Professional output. Trusted client and seller experiences.</p><Link href="/workspace">Open {platform.shortName} <b>→</b></Link></section>
  <footer className="landing-footer"><Link href="/" className="landing-logo"><i>{initial}</i><span>{platform.shortName}<small>{parent}</small></span></Link><p>Real estate, professionally operated.</p><div><Link href="/workspace">Workspace</Link><Link href="/seller">Seller portal</Link></div><small>© 2026 {platform.shortName}</small></footer>
 </main>}
