import { env } from "cloudflare:workers";
import { getChatGPTUser } from "../../chatgpt-auth";
import { requireWorkspace } from "../../../db/workspace";
import { AuthorizationError,requirePermission,writeAudit } from "../../../db/authorization";
import { hashSellerToken,sellerEmail,sellerReportCopy,validSellerEmail } from "../../../db/seller-policy";
export const dynamic="force-dynamic";
const denied=(error:unknown)=>error instanceof AuthorizationError?Response.json({error:error.message},{status:403}):Response.json({error:"Seller workspace could not be updated."},{status:500});
async function agencyContext(){const user=await getChatGPTUser();if(!user)return null;const workspace=await requireWorkspace(user);await requirePermission(workspace,"seller.manage");return{user,workspace}}
export async function GET(){try{const context=await agencyContext();if(!context)return Response.json({error:"Sign in is required."},{status:401});const agencyId=context.workspace.agencyId;const [properties,grants,reports]=await Promise.all([env.DB.prepare("SELECT id,title,location,status,reference AS ref FROM properties WHERE agency_id=? ORDER BY updated_at DESC").bind(agencyId).all(),env.DB.prepare("SELECT g.id,g.property_id AS propertyId,g.email,g.expires_at AS expiresAt,g.accepted_at AS acceptedAt,g.revoked_at AS revokedAt,p.title AS property FROM seller_access_grants g JOIN properties p ON p.id=g.property_id AND p.agency_id=g.agency_id WHERE g.agency_id=? ORDER BY g.created_at DESC").bind(agencyId).all(),env.DB.prepare("SELECT r.id,r.property_id AS propertyId,p.title AS property,r.period_start AS periodStart,r.period_end AS periodEnd,r.views,r.enquiries,r.viewings,r.summary,r.recommended_action AS recommendedAction,r.status,r.approved_at AS approvedAt FROM seller_reports r JOIN properties p ON p.id=r.property_id AND p.agency_id=r.agency_id WHERE r.agency_id=? ORDER BY r.period_end DESC").bind(agencyId).all()]);return Response.json({properties:properties.results,grants:grants.results,reports:reports.results})}catch(error){return denied(error)}}
export async function POST(request:Request){try{const context=await agencyContext();if(!context)return Response.json({error:"Sign in is required."},{status:401});const body=await request.json() as Record<string,unknown>,agencyId=context.workspace.agencyId,propertyId=String(body.propertyId||"");const property=await env.DB.prepare("SELECT id,title FROM properties WHERE id=? AND agency_id=?").bind(propertyId,agencyId).first<{id:string;title:string}>();if(!property)return Response.json({error:"Property was not found."},{status:404});if(body.action==="invite"){const email=sellerEmail(body.email);if(!validSellerEmail(email))return Response.json({error:"Enter a valid seller email address."},{status:400});await env.DB.prepare("UPDATE seller_access_grants SET revoked_at=CURRENT_TIMESTAMP WHERE agency_id=? AND property_id=? AND lower(email)=? AND revoked_at IS NULL").bind(agencyId,propertyId,email).run();const id=crypto.randomUUID(),token=crypto.randomUUID()+crypto.randomUUID().replaceAll("-",""),expiresAt=new Date(Date.now()+7*86400000).toISOString(),contact=await env.DB.prepare("SELECT id FROM contacts WHERE agency_id=? AND email_normalized=? LIMIT 1").bind(agencyId,email).first<{id:string}>();await env.DB.prepare("INSERT INTO seller_access_grants (id,agency_id,property_id,contact_id,email,token_hash,expires_at,invited_by) VALUES (?,?,?,?,?,?,?,?)").bind(id,agencyId,propertyId,contact?.id||null,email,await hashSellerToken(token),expiresAt,context.user.userId).run();await writeAudit(context.workspace,"seller.access.invited","seller_access_grant",id,{propertyId,email});return Response.json({grant:{id,propertyId,email,property:property.title,expiresAt,acceptPath:`/seller?token=${encodeURIComponent(token)}`}},{status:201})}
if(body.action==="create_report"){const periodEnd=new Date(),periodStart=new Date(periodEnd.getTime()-7*86400000),start=periodStart.toISOString(),end=periodEnd.toISOString();const [viewRow,enquiryRow,viewingRow]=await Promise.all([env.DB.prepare("SELECT COUNT(*) AS count FROM public_events WHERE agency_id=? AND property_id=? AND event_type='property_view' AND created_at>=? AND created_at<=?").bind(agencyId,propertyId,start,end).first<{count:number}>(),env.DB.prepare("SELECT COUNT(*) AS count FROM enquiries WHERE agency_id=? AND property_id=? AND created_at>=? AND created_at<=?").bind(agencyId,propertyId,start,end).first<{count:number}>(),env.DB.prepare("SELECT COUNT(*) AS count FROM viewings WHERE agency_id=? AND property_id=? AND starts_at>=? AND starts_at<=? AND status IN ('Confirmed','Completed')").bind(agencyId,propertyId,start,end).first<{count:number}>()]),views=Number(viewRow?.count||0),enquiries=Number(enquiryRow?.count||0),viewings=Number(viewingRow?.count||0),copy=sellerReportCopy(property.title,views,enquiries,viewings),id=crypto.randomUUID();await env.DB.prepare("INSERT INTO seller_reports (id,agency_id,property_id,period_start,period_end,views,enquiries,viewings,summary,recommended_action,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?)").bind(id,agencyId,propertyId,start,end,views,enquiries,viewings,copy.summary,copy.recommendedAction,context.user.userId).run();await writeAudit(context.workspace,"seller.report.created","seller_report",id,{propertyId,views,enquiries,viewings});return Response.json({report:{id,propertyId,property:property.title,periodStart:start,periodEnd:end,views,enquiries,viewings,summary:copy.summary,recommendedAction:copy.recommendedAction,status:"draft"}},{status:201})}
return Response.json({error:"Unsupported seller action."},{status:400})}catch(error){return denied(error)}}
export async function PATCH(request:Request){try{const context=await agencyContext();if(!context)return Response.json({error:"Sign in is required."},{status:401});const body=await request.json() as Record<string,unknown>,id=String(body.id||""),action=String(body.action||"");if(action==="approve_report"){const result=await env.DB.prepare("UPDATE seller_reports SET status='approved',approved_by=?,approved_at=CURRENT_TIMESTAMP WHERE id=? AND agency_id=? AND status='draft'").bind(context.user.userId,id,context.workspace.agencyId).run();if(!result.meta.changes)return Response.json({error:"Draft report was not found."},{status:404});await writeAudit(context.workspace,"seller.report.approved","seller_report",id);return Response.json({approved:true})}if(action==="revoke_access"){const result=await env.DB.prepare("UPDATE seller_access_grants SET revoked_at=CURRENT_TIMESTAMP WHERE id=? AND agency_id=? AND revoked_at IS NULL").bind(id,context.workspace.agencyId).run();if(!result.meta.changes)return Response.json({error:"Active seller access was not found."},{status:404});await writeAudit(context.workspace,"seller.access.revoked","seller_access_grant",id);return Response.json({revoked:true})}return Response.json({error:"Unsupported seller action."},{status:400})}catch(error){return denied(error)}}
