import { env } from "cloudflare:workers";
import type { WorkspaceContext } from "./workspace";

const AGENCY_TABLES=["agency_settings","agency_memberships","team_invitations","roles","audit_logs","agency_subscriptions","billing_invoices","billing_events","contacts","contact_activities","properties","property_feature_definitions","enquiries","next_actions","public_intake_attempts","public_events","media_assets","mandates","property_verification_items","property_activation_channels","property_status_events","viewings","documents","document_permissions","branches","branch_memberships","offers","seller_access_grants","seller_reports","seller_report_schedules","seller_deliveries","property_requirements","property_matches","shortlists","shortlist_items","deal_stages","deals","deal_stage_events","deal_commission_splits","domain_events","automation_rule_versions","automation_executions","notifications","notification_deliveries","marketing_template_versions","marketing_render_jobs","marketing_outputs","marketing_copy_versions","managed_properties","leases","rent_charges","rent_payments","payment_allocations","rent_receipts","tenancy_deposits","property_expenses","landlord_statements"] as const;
const runtime=()=>env as unknown as{MEDIA?:R2Bucket;BACKUP_ENCRYPTION_KEY?:string};
const hex=(bytes:ArrayBuffer|Uint8Array)=>[...new Uint8Array(bytes instanceof Uint8Array?bytes.buffer:bytes)].map(x=>x.toString(16).padStart(2,"0")).join("");
const bucket=()=>{const value=runtime().MEDIA;if(!value)throw new Error("Backup storage is unavailable.");return value};
async function encryptionKey(){const encoded=runtime().BACKUP_ENCRYPTION_KEY;if(!encoded)throw new Error("Backup encryption is not configured.");const raw=Uint8Array.from(atob(encoded),c=>c.charCodeAt(0));if(raw.byteLength!==32)throw new Error("Backup encryption configuration is invalid.");return crypto.subtle.importKey("raw",raw,"AES-GCM",false,["encrypt","decrypt"])}

export async function createAgencyBackup(workspace:WorkspaceContext,actorUserId:string,force=false){
 const a=workspace.agencyId;if(!force){const existing=await env.DB.prepare("SELECT id,status,completed_at completedAt FROM backup_snapshots WHERE agency_id=? AND started_at>=datetime('now','-23 hours') AND status IN ('pending','complete') ORDER BY started_at DESC LIMIT 1").bind(a).first();if(existing)return existing}
 const id=crypto.randomUUID(),objectKey=`tenants/${a}/backups/${new Date().toISOString().replaceAll(":","-")}-${id}.estara-backup`,counts:Record<string,number>={};
 await env.DB.prepare("INSERT INTO backup_snapshots(id,agency_id,status,created_by) VALUES(?,?,'pending',?)").bind(id,a,actorUserId).run();
 try{
  const agency=await env.DB.prepare("SELECT * FROM agencies WHERE id=?").bind(a).first(),data:Record<string,unknown[]>={};
  for(const table of AGENCY_TABLES){const rows=await env.DB.prepare(`SELECT * FROM ${table} WHERE agency_id=?`).bind(a).all();data[table]=rows.results;counts[table]=rows.results.length}const rolePermissions=await env.DB.prepare("SELECT rp.* FROM role_permissions rp JOIN roles r ON r.id=rp.role_id WHERE r.agency_id=?").bind(a).all();data.role_permissions=rolePermissions.results;counts.role_permissions=rolePermissions.results.length;
  const payload=new TextEncoder().encode(JSON.stringify({format:"estara-agency-backup",version:1,createdAt:new Date().toISOString(),agency,tables:data})),iv=crypto.getRandomValues(new Uint8Array(12)),cipher=new Uint8Array(await crypto.subtle.encrypt({name:"AES-GCM",iv},await encryptionKey(),payload)),encrypted=new Uint8Array(iv.byteLength+cipher.byteLength);encrypted.set(iv);encrypted.set(cipher,iv.byteLength);const checksum=hex(await crypto.subtle.digest("SHA-256",encrypted));
  await bucket().put(objectKey,encrypted,{httpMetadata:{contentType:"application/octet-stream"},customMetadata:{agencyId:a,backupId:id,algorithm:"AES-256-GCM",checksum}});
  await env.DB.batch([env.DB.prepare("UPDATE backup_snapshots SET object_key=?,status='complete',encrypted_bytes=?,checksum_sha256=?,table_counts=?,completed_at=CURRENT_TIMESTAMP WHERE id=? AND agency_id=?").bind(objectKey,encrypted.byteLength,checksum,JSON.stringify(counts),id,a),env.DB.prepare("INSERT INTO audit_logs(id,agency_id,actor_user_id,action,resource_type,resource_id,detail) VALUES(?,?,?,?,?,?,?)").bind(crypto.randomUUID(),a,actorUserId,"backup.completed","backup_snapshot",id,JSON.stringify({encryptedBytes:encrypted.byteLength,checksum,automatic:!force}))]);
  const expired=await env.DB.prepare("SELECT id,object_key objectKey FROM backup_snapshots WHERE agency_id=? AND status='complete' AND completed_at<datetime('now','-35 days')").bind(a).all<{id:string;objectKey:string}>();for(const old of expired.results)if(old.objectKey)await bucket().delete(old.objectKey);if(expired.results.length)await env.DB.prepare("DELETE FROM backup_snapshots WHERE agency_id=? AND completed_at<datetime('now','-35 days')").bind(a).run();
  return{id,status:"complete",completedAt:new Date().toISOString(),encryptedBytes:encrypted.byteLength,checksum,counts};
 }catch(error){const reason=error instanceof Error?error.message.slice(0,240):"Backup failed";await env.DB.prepare("UPDATE backup_snapshots SET status='failed',failure_reason=? WHERE id=? AND agency_id=?").bind(reason,id,a).run();throw error}
}

export async function backupStatus(workspace:WorkspaceContext){const rows=await env.DB.prepare("SELECT id,status,encrypted_bytes encryptedBytes,checksum_sha256 checksum,table_counts tableCounts,started_at startedAt,completed_at completedAt,failure_reason failureReason FROM backup_snapshots WHERE agency_id=? ORDER BY started_at DESC LIMIT 20").bind(workspace.agencyId).all();return rows.results}

export async function verifyAgencyBackup(workspace:WorkspaceContext,actorUserId:string,id?:string){const row=id?await env.DB.prepare("SELECT id,object_key objectKey,checksum_sha256 checksum FROM backup_snapshots WHERE id=? AND agency_id=? AND status='complete'").bind(id,workspace.agencyId).first<{id:string;objectKey:string;checksum:string}>():await env.DB.prepare("SELECT id,object_key objectKey,checksum_sha256 checksum FROM backup_snapshots WHERE agency_id=? AND status='complete' ORDER BY completed_at DESC LIMIT 1").bind(workspace.agencyId).first<{id:string;objectKey:string;checksum:string}>();if(!row)throw new Error("No completed backup is available for a recovery drill.");const object=await bucket().get(row.objectKey);if(!object)throw new Error("The encrypted backup object is unavailable.");const encrypted=new Uint8Array(await object.arrayBuffer()),checksum=hex(await crypto.subtle.digest("SHA-256",encrypted));if(checksum!==row.checksum)throw new Error("Backup integrity verification failed.");const iv=encrypted.slice(0,12),plain=await crypto.subtle.decrypt({name:"AES-GCM",iv},await encryptionKey(),encrypted.slice(12)),manifest=JSON.parse(new TextDecoder().decode(plain));if(manifest.format!=="estara-agency-backup"||manifest.agency?.id!==workspace.agencyId||!manifest.tables)throw new Error("Backup recovery manifest is invalid.");const tableCount=Object.keys(manifest.tables).length,recordCount=Object.values(manifest.tables as Record<string,unknown[]>).reduce((sum,rows)=>sum+rows.length,0);await env.DB.prepare("INSERT INTO audit_logs(id,agency_id,actor_user_id,action,resource_type,resource_id,detail) VALUES(?,?,?,?,?,?,?)").bind(crypto.randomUUID(),workspace.agencyId,actorUserId,"backup.restore_drill.completed","backup_snapshot",row.id,JSON.stringify({checksum,tableCount,recordCount})).run();return{verified:true,backupId:row.id,checksum,tableCount,recordCount,verifiedAt:new Date().toISOString()}}

export async function runDueBackups(actorUserId="system:backup-monitor"){const agencies=await env.DB.prepare("SELECT id,name FROM agencies WHERE NOT EXISTS(SELECT 1 FROM backup_snapshots b WHERE b.agency_id=agencies.id AND b.status='complete' AND b.completed_at>=datetime('now','-23 hours')) LIMIT 20").all<{id:string;name:string}>(),results=[];for(const agency of agencies.results){try{results.push(await createAgencyBackup({agencyId:agency.id,agencyName:agency.name,userId:actorUserId},actorUserId))}catch(error){results.push({agencyId:agency.id,status:"failed",error:error instanceof Error?error.message:"Backup failed"})}}return results}
