export const SUBSCRIPTION_STATES=["free","trialing","pending_payment","pending_manual_review","active","past_due","grace","trial_expired","suspended","canceled","expired"] as const;export type SubscriptionState=typeof SUBSCRIPTION_STATES[number];
export const AGENCY_STATUSES=["active","suspended","disabled","archived"] as const;export type AgencyStatus=typeof AGENCY_STATUSES[number];
export const MANUAL_PAYMENT_STATUSES=["awaiting_payment","proof_submitted","under_review","approved","rejected","resubmission_requested","expired","cancelled"] as const;export type ManualPaymentStatus=typeof MANUAL_PAYMENT_STATUSES[number];
export const PAYMENT_METHOD_TYPES=["bank_transfer","ecocash","onemoney","innbucks","cash","mobile_money","stripe","other"] as const;export type PaymentMethodType=typeof PAYMENT_METHOD_TYPES[number];
const transitions:Record<SubscriptionState,readonly SubscriptionState[]>={free:["trialing","pending_payment","active","suspended","canceled"],trialing:["active","pending_payment","grace","trial_expired","suspended","canceled","expired"],pending_payment:["pending_manual_review","active","canceled","expired"],pending_manual_review:["pending_payment","active","canceled"],active:["pending_payment","past_due","grace","suspended","canceled","expired"],past_due:["pending_payment","active","grace","suspended","canceled","expired"],grace:["active","pending_payment","suspended","canceled","expired"],trial_expired:["free","pending_payment","active","canceled"],suspended:["active","canceled"],canceled:[],expired:["active","pending_payment","canceled"]};
export function canTransitionSubscription(from:string,to:string):to is SubscriptionState{return SUBSCRIPTION_STATES.includes(to as SubscriptionState)&&transitions[from as SubscriptionState]?.includes(to as SubscriptionState)===true}
export function canSetAgencyStatus(value:string):value is AgencyStatus{return AGENCY_STATUSES.includes(value as AgencyStatus)}
export function canReviewManualPayment(value:string):value is ManualPaymentStatus{return ["proof_submitted","under_review","rejected","resubmission_requested","approved"].includes(value)}
export function subscriptionLabel(value:string){return ({free:"Free",trialing:"Trial",pending_payment:"Pending Payment",pending_manual_review:"Manual Review",active:"Active",past_due:"Past Due",grace:"Grace Period",trial_expired:"Trial Expired",suspended:"Suspended",canceled:"Cancelled",expired:"Expired"} as Record<string,string>)[value]||"Unassigned"}
export function agencyStatusLabel(value:string){return ({active:"Active",suspended:"Suspended",disabled:"Disabled",archived:"Archived"} as Record<string,string>)[value]||"Unknown"}
export function paymentMethodLabel(value:string){return ({bank_transfer:"Bank transfer",ecocash:"EcoCash",onemoney:"OneMoney",innbucks:"InnBucks",cash:"Cash",mobile_money:"Mobile money",stripe:"Card or online payment",other:"Other"} as Record<string,string>)[value]||"Payment method"}
export function manualPaymentStatusLabel(value:string){return ({awaiting_payment:"Awaiting payment",proof_submitted:"Proof submitted",under_review:"Under review",approved:"Approved",rejected:"Rejected",resubmission_requested:"Resubmission requested",expired:"Expired",cancelled:"Cancelled"} as Record<string,string>)[value]||"Pending"}
export function calculateInvoiceDiscount(subtotalMinor:number,coupon?:{kind:string;amount:number}|null){const subtotal=Math.max(0,Math.round(subtotalMinor));if(!coupon)return 0;if(coupon.kind==="percent")return Math.min(subtotal,Math.round(subtotal*Math.min(100,Math.max(0,coupon.amount))/100));if(coupon.kind==="fixed")return Math.min(subtotal,Math.max(0,Math.round(coupon.amount)));return 0}
export function invoiceTotal(subtotalMinor:number,coupon?:{kind:string;amount:number}|null){return Math.max(0,Math.round(subtotalMinor)-calculateInvoiceDiscount(subtotalMinor,coupon))}
