export const SUBSCRIPTION_STATES=["trialing","active","past_due","grace","suspended","canceled","expired"] as const;export type SubscriptionState=typeof SUBSCRIPTION_STATES[number];
export const AGENCY_STATUSES=["active","suspended","disabled","archived"] as const;export type AgencyStatus=typeof AGENCY_STATUSES[number];
const transitions:Record<SubscriptionState,readonly SubscriptionState[]>={trialing:["active","grace","suspended","canceled","expired"],active:["past_due","grace","suspended","canceled"],past_due:["active","grace","suspended","canceled"],grace:["active","suspended","canceled"],suspended:["active","canceled"],canceled:[],expired:["active","canceled"]};
export function canTransitionSubscription(from:string,to:string):to is SubscriptionState{return SUBSCRIPTION_STATES.includes(to as SubscriptionState)&&transitions[from as SubscriptionState]?.includes(to as SubscriptionState)===true}
export function canSetAgencyStatus(value:string):value is AgencyStatus{return AGENCY_STATUSES.includes(value as AgencyStatus)}
export function subscriptionLabel(value:string){return ({trialing:"Trial",active:"Active",past_due:"Past Due",grace:"Grace Period",suspended:"Suspended",canceled:"Cancelled",expired:"Expired"} as Record<string,string>)[value]||"Unassigned"}
export function agencyStatusLabel(value:string){return ({active:"Active",suspended:"Suspended",disabled:"Disabled",archived:"Archived"} as Record<string,string>)[value]||"Unknown"}
export function calculateInvoiceDiscount(subtotalMinor:number,coupon?:{kind:string;amount:number}|null){const subtotal=Math.max(0,Math.round(subtotalMinor));if(!coupon)return 0;if(coupon.kind==="percent")return Math.min(subtotal,Math.round(subtotal*Math.min(100,Math.max(0,coupon.amount))/100));if(coupon.kind==="fixed")return Math.min(subtotal,Math.max(0,Math.round(coupon.amount)));return 0}
export function invoiceTotal(subtotalMinor:number,coupon?:{kind:string;amount:number}|null){return Math.max(0,Math.round(subtotalMinor)-calculateInvoiceDiscount(subtotalMinor,coupon))}
