import { env } from "cloudflare:workers";
export const DEFAULT_PLAN_IDS={starter:"plan-starter-v1",professional:"plan-professional-v1"} as const;
export type AgencyPlan={subscriptionId:string;state:string;planVersionId:string;planKey:string;planName:string;priceMinor:number;currency:string;entitlements:Record<string,boolean>;limits:Record<string,number>;trialEndsAt:string|null;graceEndsAt:string|null;currentPeriodEndsAt:string|null};
const parse=<T extends Record<string,unknown>>(value:string,fallback:T)=>{try{return JSON.parse(value) as T}catch{return fallback}};
export async function ensurePlanCatalog(actorUserId:string){await env.DB.batch([env.DB.prepare("INSERT OR IGNORE INTO plan_versions (id,plan_key,version,name,currency,price_minor,billing_period,entitlements,limits,status,published_at,created_by) VALUES (?,?,?,?,?,?,?,?,?,'published',CURRENT_TIMESTAMP,?)").bind(DEFAULT_PLAN_IDS.starter,"starter",1,"Starter","USD",0,"month",JSON.stringify({publicWebsite:true,marketing:true,sellerPortal:true,automation:false,customDomains:false}),JSON.stringify({maxProperties:25,maxUsers:3,maxBranches:1}),actorUserId),env.DB.prepare("INSERT OR IGNORE INTO plan_versions (id,plan_key,version,name,currency,price_minor,billing_period,entitlements,limits,status,published_at,created_by) VALUES (?,?,?,?,?,?,?,?,?,'published',CURRENT_TIMESTAMP,?)").bind(DEFAULT_PLAN_IDS.professional,"professional",1,"Professional","USD",4900,"month",JSON.stringify({publicWebsite:true,marketing:true,sellerPortal:true,automation:true,customDomains:true}),JSON.stringify({maxProperties:500,maxUsers:25,maxBranches:5}),actorUserId)])}
export async function ensureAgencySubscription(agencyId:string,actorUserId:string){await ensurePlanCatalog(actorUserId);const existing=await env.DB.prepare("SELECT id FROM agency_subscriptions WHERE agency_id=?").bind(agencyId).first();if(existing)return;const now=new Date(),trialEnd=new Date(now.getTime()+14*86400000);await env.DB.prepare("INSERT OR IGNORE INTO agency_subscriptions (id,agency_id,plan_version_id,state,trial_starts_at,trial_ends_at,current_period_starts_at,current_period_ends_at,updated_by) VALUES (?,?,?,'trialing',?,?,?,?,?)").bind(crypto.randomUUID(),agencyId,DEFAULT_PLAN_IDS.starter,now.toISOString(),trialEnd.toISOString(),now.toISOString(),trialEnd.toISOString(),actorUserId).run()}
export async function resolveAgencyPlan(agencyId:string,actorUserId:string):Promise<AgencyPlan>{await ensureAgencySubscription(agencyId,actorUserId);const row=await env.DB.prepare("SELECT s.id AS subscriptionId,s.state,s.plan_version_id AS planVersionId,s.trial_ends_at AS trialEndsAt,s.grace_ends_at AS graceEndsAt,s.current_period_ends_at AS currentPeriodEndsAt,p.plan_key AS planKey,p.name AS planName,p.price_minor AS priceMinor,p.currency,p.entitlements,p.limits FROM agency_subscriptions s JOIN plan_versions p ON p.id=s.plan_version_id WHERE s.agency_id=?").bind(agencyId).first<any>();if(!row)throw new Error("Agency subscription is unavailable.");return{...row,entitlements:parse(row.entitlements,{}),limits:parse(row.limits,{})} as AgencyPlan}
export class SubscriptionAccessError extends Error{constructor(message="This agency subscription is suspended."){super(message)}}
export class PlanLimitError extends Error{constructor(message:string){super(message)}}
export async function requireAgencyOperational(agencyId:string,actorUserId:string){const plan=await resolveAgencyPlan(agencyId,actorUserId);if(plan.state==="suspended"||plan.state==="canceled")throw new SubscriptionAccessError();return plan}
export async function requireCapacity(agencyId:string,actorUserId:string,resource:"properties"|"users"){const plan=await requireAgencyOperational(agencyId,actorUserId),limitKey=resource==="properties"?"maxProperties":"maxUsers",limit=Number(plan.limits[limitKey]||0),table=resource==="properties"?"properties":"agency_memberships";if(limit>0){const row=await env.DB.prepare(`SELECT COUNT(*) AS count FROM ${table} WHERE agency_id=?`).bind(agencyId).first<{count:number}>();if(Number(row?.count||0)>=limit)throw new PlanLimitError(`${plan.planName} allows up to ${limit} ${resource}. Upgrade the plan before adding another.`)}return plan}
