import { env } from "cloudflare:workers";
export const DEFAULT_PLAN_IDS={starter:"plan-starter-v1",professional:"plan-professional-v1"} as const;
export type AgencyPlan={subscriptionId:string;state:string;agencyStatus:string;planVersionId:string;planKey:string;planName:string;priceMinor:number;currency:string;entitlements:Record<string,boolean>;limits:Record<string,number>;trialEndsAt:string|null;graceEndsAt:string|null;currentPeriodEndsAt:string|null;expiredAt:string|null};
const parse=<T extends Record<string,unknown>>(value:string,fallback:T)=>{try{return JSON.parse(value) as T}catch{return fallback}};
export const PLAN_ENTITLEMENT_KEYS=["publicWebsite","customDomains","whiteLabel","marketingStudio","sellerPortal","buyerShortlist","propertyManagement","dealPipeline","matchingEngine","automation","apiAccess","webhooks","wordpressConnector","webflowConnector","propertyPortalIntegrations","accountingIntegrations","advancedRoles","branchPermissions","backups","reports","aiStudio","documents","developments","teamInvitations","billingModule"] as const;
export const PLAN_LIMIT_DEFAULTS={maxProperties:25,maxUsers:3,maxBranches:1,maxPublicWebsites:1,maxCustomDomains:0,maxMonthlyMarketingExports:25,maxStoredMediaMb:1024,maxMediaUploadMb:12,maxMonthlyEnquiries:250,maxApiCredentials:1,maxWebhookSubscriptions:1,maxWebhookDeliveries:1000,maxAutomationRules:0,maxSellerPortals:10,maxDocuments:100,maxDevelopments:0,maxCustomRoles:0,trialDays:14,graceDays:7,auditRetentionDays:30} as const;
export const starterEntitlements={publicWebsite:true,customDomains:false,whiteLabel:false,marketingStudio:true,sellerPortal:true,buyerShortlist:true,propertyManagement:false,dealPipeline:true,matchingEngine:false,automation:false,apiAccess:false,webhooks:false,wordpressConnector:false,webflowConnector:false,propertyPortalIntegrations:false,accountingIntegrations:false,advancedRoles:false,branchPermissions:true,backups:false,reports:true,aiStudio:false,documents:true,developments:false,teamInvitations:true,billingModule:false};
export const professionalEntitlements={publicWebsite:true,customDomains:true,whiteLabel:true,marketingStudio:true,sellerPortal:true,buyerShortlist:true,propertyManagement:true,dealPipeline:true,matchingEngine:true,automation:true,apiAccess:true,webhooks:true,wordpressConnector:true,webflowConnector:true,propertyPortalIntegrations:true,accountingIntegrations:true,advancedRoles:true,branchPermissions:true,backups:true,reports:true,aiStudio:true,documents:true,developments:true,teamInvitations:true,billingModule:true};
export const starterLimits={...PLAN_LIMIT_DEFAULTS};
export const professionalLimits={...PLAN_LIMIT_DEFAULTS,maxProperties:500,maxUsers:25,maxBranches:5,maxCustomDomains:3,maxMonthlyMarketingExports:1000,maxStoredMediaMb:10240,maxMediaUploadMb:25,maxMonthlyEnquiries:5000,maxApiCredentials:10,maxWebhookSubscriptions:10,maxWebhookDeliveries:50000,maxAutomationRules:50,maxSellerPortals:500,maxDocuments:5000,maxDevelopments:25,maxCustomRoles:25,trialDays:14,graceDays:7,auditRetentionDays:365};
export async function ensurePlanCatalog(actorUserId:string){await env.DB.batch([env.DB.prepare("INSERT OR IGNORE INTO plan_versions (id,plan_key,version,name,currency,price_minor,billing_period,entitlements,limits,status,published_at,created_by) VALUES (?,?,?,?,?,?,?,?,?,'published',CURRENT_TIMESTAMP,?)").bind(DEFAULT_PLAN_IDS.starter,"starter",1,"Starter","USD",0,"month",JSON.stringify(starterEntitlements),JSON.stringify(starterLimits),actorUserId),env.DB.prepare("INSERT OR IGNORE INTO plan_versions (id,plan_key,version,name,currency,price_minor,billing_period,entitlements,limits,status,published_at,created_by) VALUES (?,?,?,?,?,?,?,?,?,'published',CURRENT_TIMESTAMP,?)").bind(DEFAULT_PLAN_IDS.professional,"professional",1,"Professional","USD",4900,"month",JSON.stringify(professionalEntitlements),JSON.stringify(professionalLimits),actorUserId)])}
export async function ensureAgencySubscription(agencyId:string,actorUserId:string){await ensurePlanCatalog(actorUserId);const existing=await env.DB.prepare("SELECT id FROM agency_subscriptions WHERE agency_id=?").bind(agencyId).first();if(existing)return;const now=new Date(),trialEnd=new Date(now.getTime()+14*86400000);await env.DB.prepare("INSERT OR IGNORE INTO agency_subscriptions (id,agency_id,plan_version_id,state,trial_starts_at,trial_ends_at,current_period_starts_at,current_period_ends_at,updated_by) VALUES (?,?,?,'trialing',?,?,?,?,?)").bind(crypto.randomUUID(),agencyId,DEFAULT_PLAN_IDS.starter,now.toISOString(),trialEnd.toISOString(),now.toISOString(),trialEnd.toISOString(),actorUserId).run()}
export async function resolveAgencyPlan(agencyId:string,actorUserId:string):Promise<AgencyPlan>{await ensureAgencySubscription(agencyId,actorUserId);await syncSubscriptionLifecycle(agencyId,actorUserId);const row=await env.DB.prepare("SELECT s.id AS subscriptionId,s.state,a.status AS agencyStatus,s.plan_version_id AS planVersionId,s.trial_ends_at AS trialEndsAt,s.grace_ends_at AS graceEndsAt,s.current_period_ends_at AS currentPeriodEndsAt,s.expired_at AS expiredAt,p.plan_key AS planKey,p.name AS planName,p.price_minor AS priceMinor,p.currency,p.entitlements,p.limits FROM agency_subscriptions s JOIN agencies a ON a.id=s.agency_id JOIN plan_versions p ON p.id=s.plan_version_id WHERE s.agency_id=?").bind(agencyId).first<any>();if(!row)throw new Error("Agency subscription is unavailable.");return{...row,entitlements:parse(row.entitlements,{}),limits:parse(row.limits,{})} as AgencyPlan}
async function syncSubscriptionLifecycle(agencyId:string,actorUserId:string){const row=await env.DB.prepare("SELECT id,state,trial_ends_at AS trialEndsAt,grace_ends_at AS graceEndsAt FROM agency_subscriptions WHERE agency_id=?").bind(agencyId).first<any>();if(!row)return;const now=Date.now();if(row.state==="trialing"&&row.trialEndsAt&&Date.parse(row.trialEndsAt)<now){await env.DB.prepare("UPDATE agency_subscriptions SET state='expired',expired_at=CURRENT_TIMESTAMP,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND state='trialing'").bind(actorUserId,row.id).run()}else if(row.state==="grace"&&row.graceEndsAt&&Date.parse(row.graceEndsAt)<now){await env.DB.prepare("UPDATE agency_subscriptions SET state='suspended',suspended_at=CURRENT_TIMESTAMP,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND state='grace'").bind(actorUserId,row.id).run()}}
export class SubscriptionAccessError extends Error{constructor(message="This agency is not currently operational."){super(message)}}
export class PlanLimitError extends Error{constructor(message:string){super(message)}}
export async function requireAgencyOperational(agencyId:string,actorUserId:string){const plan=await resolveAgencyPlan(agencyId,actorUserId);if(plan.state==="suspended"||plan.state==="canceled"||plan.state==="expired"||["suspended","disabled","archived"].includes(plan.agencyStatus))throw new SubscriptionAccessError();return plan}
export async function requireEntitlement(agencyId:string,actorUserId:string,entitlement:string){const plan=await requireAgencyOperational(agencyId,actorUserId);if(plan.entitlements[entitlement]!==true)throw new PlanLimitError(`${plan.planName} does not include ${entitlement.replace(/([A-Z])/g," $1").toLowerCase()}. Assign an eligible plan before enabling it.`);return plan}
export async function requireCapacity(agencyId:string,actorUserId:string,resource:"properties"|"users"|"branches"){const plan=await requireAgencyOperational(agencyId,actorUserId),map={properties:["maxProperties","properties"],users:["maxUsers","agency_memberships"],branches:["maxBranches","branches"]} as const,[limitKey,table]=map[resource],limit=Number(plan.limits[limitKey]||0);if(limit>0){const row=await env.DB.prepare(`SELECT COUNT(*) AS count FROM ${table} WHERE agency_id=?`).bind(agencyId).first<{count:number}>();if(Number(row?.count||0)>=limit)throw new PlanLimitError(`${plan.planName} allows up to ${limit} ${resource}. Upgrade the plan before adding another.`)}return plan}
