export const PROPERTY_STATUSES=["Draft","Available","Under Offer","Sold","Let","Withdrawn","Expired"] as const;
export type PropertyStatus=typeof PROPERTY_STATUSES[number];
const transitions:Record<PropertyStatus,readonly PropertyStatus[]>={Draft:["Available","Withdrawn"],Available:["Under Offer","Sold","Let","Withdrawn","Expired"],"Under Offer":["Available","Sold","Let","Withdrawn","Expired"],Sold:[],Let:[],Withdrawn:["Draft"],Expired:["Draft","Available"]};
export function canTransitionProperty(from:string,to:string){return PROPERTY_STATUSES.includes(from as PropertyStatus)&&PROPERTY_STATUSES.includes(to as PropertyStatus)&&transitions[from as PropertyStatus].includes(to as PropertyStatus)}
export const ACTIVATION_CHANNELS=["website","share_page","whatsapp","facebook","instagram","brochure","buyer_matching","seller_reporting","viewing_requests"] as const;
export const VERIFICATION_ITEMS=["ownership","mandate","price","address","description","photos"] as const;
type CompletenessInput={title?:string;transactionType?:string;propertyType?:string;priceMinor?:number;currency?:string;bedrooms?:number;bathrooms?:number;country?:string;city?:string;suburb?:string;address?:string;description?:string;ownerContactId?:string;listingAgentId?:string;mandateId?:string;photoCount?:number;landSize?:string};
export function propertyCompleteness(input:CompletenessInput){const checks=[input.title,input.transactionType,input.propertyType,Number(input.priceMinor)>0,input.currency,Number(input.bedrooms)>=0,Number(input.bathrooms)>=0,input.country,input.city,input.suburb,input.address,(input.description?.trim().length||0)>=40,input.ownerContactId,input.listingAgentId,input.mandateId,Number(input.photoCount)>=6,input.landSize];const complete=checks.filter(Boolean).length;return{percentage:Math.round(complete/checks.length*100),missing:[!input.title&&"title",!input.propertyType&&"property type",!(Number(input.priceMinor)>0)&&"price",!input.city&&"city",!input.suburb&&"suburb",!input.address&&"address",(input.description?.trim().length||0)<40&&"description",!input.ownerContactId&&"owner",!input.listingAgentId&&"listing agent",!input.mandateId&&"mandate",Number(input.photoCount)<6&&"six photos",!input.landSize&&"stand size"].filter(Boolean) as string[]}}
export function activationReady(input:CompletenessInput,verifiedKeys:string[]){const completeness=propertyCompleteness(input);const missingVerification=VERIFICATION_ITEMS.filter(item=>!verifiedKeys.includes(item));return{ready:completeness.percentage===100&&!missingVerification.length,completeness,missingVerification}}
export function statusDisablesPublicDemand(status:string){return ["Sold","Let","Withdrawn","Expired"].includes(status)}
