export const PROPERTY_STATUSES=["Draft","Available","Under Offer","Sold","Let","Withdrawn","Expired"] as const;
export type PropertyStatus=typeof PROPERTY_STATUSES[number];
const transitions:Record<PropertyStatus,readonly PropertyStatus[]>={Draft:["Available","Withdrawn"],Available:["Under Offer","Sold","Let","Withdrawn","Expired"],"Under Offer":["Available","Sold","Let","Withdrawn","Expired"],Sold:[],Let:[],Withdrawn:["Draft"],Expired:["Draft","Available"]};
export function canTransitionProperty(from:string,to:string){return PROPERTY_STATUSES.includes(from as PropertyStatus)&&PROPERTY_STATUSES.includes(to as PropertyStatus)&&transitions[from as PropertyStatus].includes(to as PropertyStatus)}
export const ACTIVATION_CHANNELS=["website","share_page","whatsapp","facebook","instagram","brochure","buyer_matching","seller_reporting","viewing_requests"] as const;
export const VERIFICATION_ITEMS=["ownership","mandate","price","address","description","photos"] as const;
type CompletenessInput={title?:string;transactionType?:string;propertyType?:string;priceMinor?:number;currency?:string;bedrooms?:number;bathrooms?:number;country?:string;city?:string;suburb?:string;address?:string;description?:string;ownerContactId?:string;listingAgentId?:string;mandateId?:string;photoCount?:number;landSize?:string};
const lower=(value?:string)=>String(value||"").toLowerCase();
export function propertyPhotoRequirement(input:CompletenessInput){const type=lower(input.propertyType),rent=lower(input.transactionType)==="rent";if(type.includes("room")||type.includes("land")||type.includes("stand"))return 1;if(rent)return 3;return 4}
export function propertyNeedsLandSize(input:CompletenessInput){const type=lower(input.propertyType),rent=lower(input.transactionType)==="rent";if(type.includes("room")||type.includes("apartment")||type.includes("flat"))return false;if(rent&&!type.includes("land")&&!type.includes("stand"))return false;return true}
export function propertyCompleteness(input:CompletenessInput){const photoRequirement=propertyPhotoRequirement(input),needsLand=propertyNeedsLandSize(input);const checks=[input.title,input.transactionType,input.propertyType,Number(input.priceMinor)>0,input.currency,Number(input.bedrooms)>=0,Number(input.bathrooms)>=0,input.country,input.city,input.suburb,input.address,(input.description?.trim().length||0)>=40,input.ownerContactId,input.listingAgentId,input.mandateId,Number(input.photoCount)>=photoRequirement,!needsLand||input.landSize];const complete=checks.filter(Boolean).length;return{percentage:Math.round(complete/checks.length*100),missing:[!input.title&&"title",!input.propertyType&&"property type",!(Number(input.priceMinor)>0)&&"price",!input.city&&"city",!input.suburb&&"suburb",!input.address&&"address",(input.description?.trim().length||0)<40&&"description",!input.ownerContactId&&"owner",!input.listingAgentId&&"listing agent",!input.mandateId&&"mandate",Number(input.photoCount)<photoRequirement&&`${photoRequirement} photo${photoRequirement===1?"":"s"}`,needsLand&&!input.landSize&&"stand size"].filter(Boolean) as string[],photoRequirement,needsLand}}
export function propertyPublishReadiness(input:CompletenessInput){const checks=[input.title,input.transactionType,input.propertyType,Number(input.priceMinor)>0,input.currency,input.city||input.suburb,Number(input.photoCount)>=1],missing=[!input.title&&"title",!input.transactionType&&"sale or rent",!input.propertyType&&"property type",!(Number(input.priceMinor)>0)&&"price",!input.currency&&"currency",!(input.city||input.suburb)&&"suburb or city",Number(input.photoCount)<1&&"1 photo"].filter(Boolean) as string[];return{ready:checks.every(Boolean),missing,percentage:Math.round(checks.filter(Boolean).length/checks.length*100)}}
export function activationReady(input:CompletenessInput,verifiedKeys:string[]){const completeness=propertyCompleteness(input);const missingVerification=VERIFICATION_ITEMS.filter(item=>!verifiedKeys.includes(item));return{ready:completeness.percentage===100&&!missingVerification.length,completeness,missingVerification}}
export function statusDisablesPublicDemand(status:string){return ["Sold","Let","Withdrawn","Expired"].includes(status)}
