export type PublicAgency={id:string;name:string;slug:string;tagline:string;primaryColor:string;accentColor:string;phone:string;whatsapp:string;email:string;website:string;businessActivities:string[];websiteTemplate:string;typography:string;responseSlaMinutes:number;logoId:string|null;portalName:string;hideParentBrand:boolean;poweredByWording:string};
export type PublicAgent={userId:string;name:string;role:string;listings:number};
export type PublicProperty={id:string;ref:string;title:string;location:string;price:string;beds:number;baths:number;photos:number;size:string;transactionType:string;heroMediaId:string|null};
const runtimeEnv=async ()=>(await import("cloudflare:workers")).env;
export async function getPublicAgency(slug:string):Promise<PublicAgency|null>{if(!/^[a-z][a-z0-9-]{3,58}[a-z0-9]$/.test(slug)||slug.includes("--"))return null;const env=await runtimeEnv(),row=await env.DB.prepare(`SELECT a.id,a.name,a.slug,s.tagline,s.primary_color AS primaryColor,s.accent_color AS accentColor,s.phone,s.whatsapp,s.email,s.website,s.business_activities AS businessActivities,s.website_template AS websiteTemplate,s.typography,s.response_sla_minutes AS responseSlaMinutes,(SELECT m.id FROM media_assets m WHERE m.agency_id=a.id AND m.kind='agency_logo' ORDER BY m.created_at DESC LIMIT 1) AS logoId,COALESCE(NULLIF(eb.portal_name,''),a.name) AS portalName,COALESCE(eb.hide_parent_brand,0) AS hideParentBrand,COALESCE(NULLIF(ps.powered_by_wording,''),'Powered by ESTARA') AS poweredByWording FROM agencies a JOIN agency_settings s ON s.agency_id=a.id LEFT JOIN enterprise_branding eb ON eb.agency_id=a.id LEFT JOIN platform_settings ps ON ps.id='default' WHERE a.slug=? AND s.onboarding_complete=1`).bind(slug).first<any>();if(!row)return null;return{...row,hideParentBrand:Boolean(row.hideParentBrand),businessActivities:JSON.parse(row.businessActivities||"[]")}}
const publicPropertyColumns=`p.id,p.reference AS ref,p.title,p.location,p.price_label AS price,p.bedrooms AS beds,p.bathrooms AS baths,p.photo_count AS photos,p.land_size AS size,p.transaction_type AS transactionType,(SELECT m.id FROM media_assets m WHERE m.agency_id=p.agency_id AND m.property_id=p.id AND m.kind='property_photo' ORDER BY m.sort_order,m.created_at LIMIT 1) AS heroMediaId`;
export async function listPublicProperties(agencyId:string,transactionType?:string){const env=await runtimeEnv(),filter=transactionType?" AND transaction_type=?":"",query=`SELECT ${publicPropertyColumns} FROM properties p WHERE agency_id=? AND status='Available'${filter} ORDER BY updated_at DESC`;const result=transactionType?await env.DB.prepare(query).bind(agencyId,transactionType).all<PublicProperty>():await env.DB.prepare(query).bind(agencyId).all<PublicProperty>();return result.results}
export async function getPublicProperty(agencyId:string,id:string){const env=await runtimeEnv();return env.DB.prepare(`SELECT ${publicPropertyColumns} FROM properties p WHERE p.id=? AND agency_id=? AND status='Available'`).bind(id,agencyId).first<PublicProperty>()}
export async function listPublicAgents(agencyId:string){const env=await runtimeEnv(),result=await env.DB.prepare("SELECT m.user_id AS userId,m.email,m.role,COUNT(p.id) AS listings FROM agency_memberships m LEFT JOIN properties p ON p.agency_id=m.agency_id AND p.listing_agent_id=m.user_id AND p.status='Available' WHERE m.agency_id=? GROUP BY m.user_id,m.email,m.role ORDER BY listings DESC,m.email LIMIT 24").bind(agencyId).all<any>();return result.results.map(row=>({userId:row.userId,name:String(row.email||"Agent").split("@")[0].replace(/[._-]+/g," ").replace(/\b\w/g,c=>c.toUpperCase()),role:String(row.role||"agent").replace(/[-_]+/g," "),listings:Number(row.listings||0)}))}
export function normalizePublicHost(host:string){return host.toLowerCase().replace(/:\d+$/,"").replace(/\.$/,"")}
export function tenantSlugFromHost(host:string,tenantDomainSuffix=""){const domain=normalizePublicHost(host),suffix=normalizePublicHost(tenantDomainSuffix).replace(/^\./,"");if(!suffix||domain===suffix||!domain.endsWith(`.${suffix}`))return null;const slug=domain.slice(0,-suffix.length-1);return /^[a-z][a-z0-9-]{3,58}[a-z0-9]$/.test(slug)&&!slug.includes("--")&&!slug.includes(".")?slug:null}
export async function getPublicAgencyByHost(host:string,tenantDomainSuffix=""):Promise<PublicAgency|null>{const domain=normalizePublicHost(host);if(!/^[a-z0-9.-]+$/.test(domain))return null;const env=await runtimeEnv(),row=await env.DB.prepare("SELECT a.slug FROM custom_domains d JOIN agencies a ON a.id=d.agency_id JOIN agency_settings s ON s.agency_id=a.id WHERE d.domain=? AND d.status='active' AND s.onboarding_complete=1 LIMIT 1").bind(domain).first<{slug:string}>();const slug=row?.slug||tenantSlugFromHost(domain,tenantDomainSuffix||env.PUBLIC_SITE_DOMAIN||"");return slug?getPublicAgency(slug):null}
