import { sql } from "drizzle-orm";
import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";
export const agencies=sqliteTable("agencies",{id:text("id").primaryKey(),name:text("name").notNull(),slug:text("slug").notNull(),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`)},t=>[uniqueIndex("idx_agencies_slug").on(t.slug)]);
export const agencyMemberships=sqliteTable("agency_memberships",{id:text("id").primaryKey(),agencyId:text("agency_id").notNull().references(()=>agencies.id),userId:text("user_id").notNull(),email:text("email").notNull(),role:text("role").notNull().default("principal"),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`)},t=>[uniqueIndex("idx_memberships_agency_user").on(t.agencyId,t.userId),index("idx_memberships_user").on(t.userId)]);
export const properties=sqliteTable("properties",{id:text("id").primaryKey(),agencyId:text("agency_id").notNull().references(()=>agencies.id),reference:text("reference").notNull(),title:text("title").notNull(),location:text("location").notNull(),priceMinor:integer("price_minor").notNull(),currency:text("currency").notNull().default("USD"),priceLabel:text("price_label").notNull(),bedrooms:integer("bedrooms").notNull().default(0),bathrooms:integer("bathrooms").notNull().default(0),status:text("status").notNull().default("Draft"),photoCount:integer("photo_count").notNull().default(0),ownerPhone:text("owner_phone").notNull().default(""),landSize:text("land_size").notNull().default(""),completeness:integer("completeness").notNull().default(0),createdBy:text("created_by").notNull(),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),updatedAt:text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`)},t=>[uniqueIndex("idx_properties_agency_reference").on(t.agencyId,t.reference),index("idx_properties_agency_status").on(t.agencyId,t.status)]);
export const enquiries=sqliteTable("enquiries",{id:text("id").primaryKey(),agencyId:text("agency_id").notNull().references(()=>agencies.id),propertyId:text("property_id").references(()=>properties.id),contactName:text("contact_name").notNull(),initials:text("initials").notNull(),propertyLabel:text("property_label").notNull(),status:text("status").notNull().default("New"),source:text("source").notNull().default("Website"),responseDueAt:text("response_due_at").notNull(),contactedAt:text("contacted_at"),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`)},t=>[index("idx_enquiries_agency_status").on(t.agencyId,t.status)]);
export const nextActions=sqliteTable("next_actions",{id:text("id").primaryKey(),agencyId:text("agency_id").notNull().references(()=>agencies.id),resourceType:text("resource_type").notNull(),resourceId:text("resource_id").notNull(),actionType:text("action_type").notNull(),reason:text("reason").notNull(),priority:text("priority").notNull().default("normal"),dueAt:text("due_at").notNull(),status:text("status").notNull().default("open"),assignedUserId:text("assigned_user_id").notNull(),completedAt:text("completed_at"),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`)},t=>[index("idx_next_actions_agency_status_due").on(t.agencyId,t.status,t.dueAt)]);

export const platformSettings=sqliteTable("platform_settings",{id:text("id").primaryKey(),platformName:text("platform_name").notNull(),shortName:text("short_name").notNull(),parentBrand:text("parent_brand").notNull().default(""),tagline:text("tagline").notNull().default(""),primaryColor:text("primary_color").notNull().default("#153b34"),supportEmail:text("support_email").notNull().default(""),supportPhone:text("support_phone").notNull().default(""),supportWhatsapp:text("support_whatsapp").notNull().default(""),defaultCountry:text("default_country").notNull().default("ZW"),defaultCurrency:text("default_currency").notNull().default("USD"),timezone:text("timezone").notNull().default("Africa/Harare"),updatedAt:text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`)});
export const agencySettings=sqliteTable("agency_settings",{agencyId:text("agency_id").primaryKey().references(()=>agencies.id),tagline:text("tagline").notNull().default(""),primaryColor:text("primary_color").notNull().default("#153b34"),accentColor:text("accent_color").notNull().default("#e6bd5f"),phone:text("phone").notNull().default(""),whatsapp:text("whatsapp").notNull().default(""),email:text("email").notNull().default(""),website:text("website").notNull().default(""),businessActivities:text("business_activities").notNull().default("[]"),websiteTemplate:text("website_template").notNull().default("classic"),onboardingComplete:integer("onboarding_complete",{mode:"boolean"}).notNull().default(false),updatedAt:text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`)});
export const roles=sqliteTable("roles",{id:text("id").primaryKey(),agencyId:text("agency_id").notNull().references(()=>agencies.id),name:text("name").notNull(),isSystem:integer("is_system",{mode:"boolean"}).notNull().default(false),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`)},t=>[uniqueIndex("idx_roles_agency_name").on(t.agencyId,t.name)]);
export const rolePermissions=sqliteTable("role_permissions",{roleId:text("role_id").notNull().references(()=>roles.id),permission:text("permission").notNull()},t=>[uniqueIndex("idx_role_permissions_role_permission").on(t.roleId,t.permission)]);
export const auditLogs=sqliteTable("audit_logs",{id:text("id").primaryKey(),agencyId:text("agency_id").references(()=>agencies.id),actorUserId:text("actor_user_id").notNull(),action:text("action").notNull(),resourceType:text("resource_type").notNull(),resourceId:text("resource_id").notNull(),detail:text("detail").notNull().default("{}"),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`)},t=>[index("idx_audit_logs_agency_created").on(t.agencyId,t.createdAt)]);
