import { env } from "cloudflare:workers";
import type { ChatGPTUser } from "../app/chatgpt-auth";
import { ensureAgencySubscription } from "./entitlements";
import { ensurePlatformIdentity } from "./platform-settings";
export type WorkspaceContext={agencyId:string;agencyName:string;userId:string};
export async function requireWorkspace(user:ChatGPTUser):Promise<WorkspaceContext>{
 const existing=await env.DB.prepare(`SELECT m.agency_id AS agencyId,a.name AS agencyName FROM agency_memberships m JOIN agencies a ON a.id=m.agency_id WHERE m.user_id=? ORDER BY m.created_at ASC LIMIT 1`).bind(user.userId).first<{agencyId:string;agencyName:string}>();
 if(existing){await ensureSettings(existing.agencyId);await ensureAgencySubscription(existing.agencyId,user.userId);await ensureLocalPreviewData(existing.agencyId,user);return{...existing,userId:user.userId}};
 const agencyId=crypto.randomUUID();
 await env.DB.batch([env.DB.prepare("INSERT INTO agencies (id,name,slug) VALUES (?,?,?)").bind(agencyId,"Prime Property",`prime-${agencyId.slice(0,8)}`),env.DB.prepare("INSERT INTO agency_memberships (id,agency_id,user_id,email,role) VALUES (?,?,?,?,?)").bind(crypto.randomUUID(),agencyId,user.userId,user.email,"principal")]);
 await ensureSettings(agencyId);await ensureAgencySubscription(agencyId,user.userId);await ensureLocalPreviewData(agencyId,user);return{agencyId,agencyName:"Prime Property",userId:user.userId};
}
export function calculateCompleteness(i:{title:string;location:string;priceMinor:number;bedrooms:number;bathrooms:number;photoCount:number;ownerPhone:string;landSize:string}){const v=[i.title,i.location,i.priceMinor>0,i.bedrooms>0,i.bathrooms>0,i.photoCount>=8,i.ownerPhone,i.landSize];return Math.round(v.filter(Boolean).length/v.length*100)}

async function ensureSettings(agencyId:string){await ensurePlatformIdentity();await env.DB.prepare("INSERT OR IGNORE INTO agency_settings (agency_id,tagline,primary_color,accent_color) VALUES (?,?,?,?)").bind(agencyId,"Property, professionally handled.","#153b34","#e6bd5f").run()}

async function ensureLocalPreviewData(agencyId:string,user:ChatGPTUser){
 if(user.userId!=="local-preview-principal")return;
 const existing=await env.DB.prepare("SELECT COUNT(*) AS count FROM properties WHERE agency_id=?").bind(agencyId).first<{count:number}>();
 if(Number(existing?.count||0)>0){await ensureLocalPreviewSellerAccess(agencyId,user);return}

 const now=Date.now(),day=86400000,iso=(offset:number)=>new Date(now+offset).toISOString();
 const propertyA=crypto.randomUUID(),propertyB=crypto.randomUUID(),propertyC=crypto.randomUUID();
 const contactBuyer=crypto.randomUUID(),contactSeller=crypto.randomUUID(),contactTenant=crypto.randomUUID();
 const enquiryA=crypto.randomUUID(),enquiryB=crypto.randomUUID();
 const stageQualified=crypto.randomUUID(),stageOffer=crypto.randomUUID(),stageDueDiligence=crypto.randomUUID(),stageWon=crypto.randomUUID(),stageLost=crypto.randomUUID();
 const dealA=crypto.randomUUID(),dealB=crypto.randomUUID();
 const grantId=crypto.randomUUID(),reportId=crypto.randomUUID();

 await env.DB.batch([
  env.DB.prepare(`UPDATE agencies SET name=?,slug=? WHERE id=?`).bind("Prime Property","prime-property",agencyId),
  env.DB.prepare(`UPDATE agency_settings SET tagline=?,phone=?,whatsapp=?,email=?,website=?,business_activities=?,website_template=?,typography=?,onboarding_complete=1,response_sla_minutes=20,updated_at=CURRENT_TIMESTAMP WHERE agency_id=?`).bind("Harare's premium property command centre","+263 77 234 9810","+263 77 234 9810","hello@primeproperty.co.zw","https://prime-property.example",JSON.stringify(["Residential sales","Residential rentals","Property management","Developments"]),"signature","modern",agencyId),
  env.DB.prepare(`INSERT OR IGNORE INTO contacts (id,agency_id,full_name,phone_e164,email_normalized,roles,requirements,notes,assigned_user_id,created_by) VALUES (?,?,?,?,?,?,?,?,?,?)`).bind(contactBuyer,agencyId,"Tariro Moyo","+263772349810","tariro@example.com",JSON.stringify(["buyer"]),"Borrowdale or Greendale, 4+ bedrooms, move-in ready","Prefers WhatsApp and weekend viewings.",user.userId,user.userId),
  env.DB.prepare(`INSERT OR IGNORE INTO contacts (id,agency_id,full_name,phone_e164,email_normalized,roles,requirements,notes,assigned_user_id,created_by) VALUES (?,?,?,?,?,?,?,?,?,?)`).bind(contactSeller,agencyId,"Sarah Ncube","+263719902221",user.email,JSON.stringify(["seller"]),"Owner of Borrowdale Residence","Wants weekly evidence-led reporting.",user.userId,user.userId),
  env.DB.prepare(`INSERT OR IGNORE INTO contacts (id,agency_id,full_name,phone_e164,email_normalized,roles,requirements,notes,assigned_user_id,created_by) VALUES (?,?,?,?,?,?,?,?,?,?)`).bind(contactTenant,agencyId,"Daniel Ncube","+263713450918","daniel@example.com",JSON.stringify(["tenant","buyer"]),"Executive rental, northern suburbs","Needs secure parking and fibre.",user.userId,user.userId),
  env.DB.prepare(`INSERT INTO properties (id,agency_id,reference,title,location,price_minor,currency,transaction_type,property_type,price_label,bedrooms,bathrooms,toilets,parking,garages,status,photo_count,owner_phone,owner_contact_id,listing_agent_id,land_size,building_size,country,province,city,suburb,address,description,features,completeness,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(propertyA,agencyId,"EST-2401","Borrowdale Residence","Borrowdale, Harare",42000000,"USD","Sale","House","US$420,000",5,4,5,4,2,"Available",12,"+263719902221",contactSeller,user.userId,"3,400 m2","520 m2","Zimbabwe","Harare","Harare","Borrowdale","Borrowdale Brooke Road","A premium family residence with generous entertainment spaces, landscaped gardens and strong seller activity.",JSON.stringify(["Pool","Borehole","Solar backup","Staff quarters"]),100,user.userId),
  env.DB.prepare(`INSERT INTO properties (id,agency_id,reference,title,location,price_minor,currency,transaction_type,property_type,price_label,bedrooms,bathrooms,toilets,parking,garages,status,photo_count,owner_phone,owner_contact_id,listing_agent_id,land_size,building_size,country,province,city,suburb,address,description,features,completeness,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(propertyB,agencyId,"EST-2402","Greendale Garden Sanctuary","Greendale, Harare",18000000,"USD","Sale","House","US$180,000",4,3,3,3,1,"Available",10,"+263719902221",contactSeller,user.userId,"2,100 m2","310 m2","Zimbabwe","Harare","Harare","Greendale","Coronation Avenue","A warm family home with mature gardens, solar support and a practical layout for entertaining.",JSON.stringify(["Garden","Solar backup","Borehole","Cottage"]),94,user.userId),
  env.DB.prepare(`INSERT INTO properties (id,agency_id,reference,title,location,price_minor,currency,transaction_type,property_type,price_label,bedrooms,bathrooms,toilets,parking,garages,status,photo_count,owner_phone,owner_contact_id,listing_agent_id,land_size,building_size,country,province,city,suburb,address,description,features,completeness,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(propertyC,agencyId,"EST-2403","Newlands Executive Townhouse","Newlands, Harare",185000,"USD","Rent","Townhouse","US$1,850 / month",3,2,3,2,1,"Draft",6,"+263719902221",contactSeller,user.userId,"650 m2","190 m2","Zimbabwe","Harare","Harare","Newlands","Princess Drive","A polished lock-up-and-go rental close to offices, schools and daily amenities.",JSON.stringify(["Security","Fibre-ready","Backup water"]),72,user.userId),
  env.DB.prepare(`INSERT INTO enquiries (id,agency_id,property_id,contact_id,assigned_user_id,stage,next_follow_up_at,contact_name,initials,property_label,status,source,response_due_at,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(enquiryA,agencyId,propertyA,contactBuyer,user.userId,"Qualified",iso(day),"Tariro Moyo","TM","Borrowdale Residence","Contacted","Website",iso(20*60000),iso(-2*60*60000)),
  env.DB.prepare(`INSERT INTO enquiries (id,agency_id,property_id,contact_id,assigned_user_id,stage,next_follow_up_at,contact_name,initials,property_label,status,source,response_due_at,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(enquiryB,agencyId,propertyC,contactTenant,user.userId,"Viewing",iso(2*day),"Daniel Ncube","DN","Newlands Executive Townhouse","New","WhatsApp",iso(-15*60000),iso(-50*60000)),
  env.DB.prepare(`INSERT INTO next_actions (id,agency_id,resource_type,resource_id,action_type,reason,priority,due_at,status,assigned_user_id) VALUES (?,?,?,?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),agencyId,"enquiry",enquiryB,"respond","Respond to Daniel Ncube about Newlands viewing","urgent",iso(-15*60000),"open",user.userId),
  env.DB.prepare(`INSERT INTO next_actions (id,agency_id,resource_type,resource_id,action_type,reason,priority,due_at,status,assigned_user_id) VALUES (?,?,?,?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),agencyId,"property",propertyC,"complete_listing","Add final media and owner mandate for Newlands townhouse","high",iso(3*60*60000),"open",user.userId),
  env.DB.prepare(`INSERT INTO viewings (id,agency_id,property_id,enquiry_id,contact_id,assigned_user_id,starts_at,ends_at,status,notes,reminder_at,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),agencyId,propertyA,enquiryA,contactBuyer,user.userId,iso(4*60*60000),iso(5*60*60000),"Confirmed","Buyer wants to inspect entertainment area and solar system.",iso(3*60*60000),user.userId),
  env.DB.prepare(`INSERT INTO viewings (id,agency_id,property_id,enquiry_id,contact_id,assigned_user_id,starts_at,ends_at,status,notes,reminder_at,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),agencyId,propertyC,enquiryB,contactTenant,user.userId,iso(day+2*60*60000),iso(day+3*60*60000),"Requested","Confirm access with landlord before sending final slot.",iso(day+60*60000),user.userId),
  env.DB.prepare(`INSERT INTO deal_stages (id,agency_id,name,position,probability,outcome,created_by) VALUES (?,?,?,?,?,?,?)`).bind(stageQualified,agencyId,"Qualified",1,20,"open",user.userId),
  env.DB.prepare(`INSERT INTO deal_stages (id,agency_id,name,position,probability,outcome,created_by) VALUES (?,?,?,?,?,?,?)`).bind(stageOffer,agencyId,"Offer",2,50,"open",user.userId),
  env.DB.prepare(`INSERT INTO deal_stages (id,agency_id,name,position,probability,outcome,created_by) VALUES (?,?,?,?,?,?,?)`).bind(stageDueDiligence,agencyId,"Due diligence",3,75,"open",user.userId),
  env.DB.prepare(`INSERT INTO deal_stages (id,agency_id,name,position,probability,outcome,created_by) VALUES (?,?,?,?,?,?,?)`).bind(stageWon,agencyId,"Closed won",4,100,"won",user.userId),
  env.DB.prepare(`INSERT INTO deal_stages (id,agency_id,name,position,probability,outcome,created_by) VALUES (?,?,?,?,?,?,?)`).bind(stageLost,agencyId,"Closed lost",5,0,"lost",user.userId),
  env.DB.prepare(`INSERT INTO deals (id,agency_id,property_id,contact_id,enquiry_id,stage_id,title,value_minor,currency,commission_basis_points,expected_close_at,status,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(dealA,agencyId,propertyA,contactBuyer,enquiryA,stageOffer,"Tariro Moyo - Borrowdale Residence",42000000,"USD",300,iso(21*day),"open",user.userId),
  env.DB.prepare(`INSERT INTO deals (id,agency_id,property_id,contact_id,enquiry_id,stage_id,title,value_minor,currency,commission_basis_points,expected_close_at,status,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(dealB,agencyId,propertyB,contactBuyer,null,stageWon,"Greendale Garden Sanctuary referral",18000000,"USD",300,iso(-7*day),"won",user.userId),
  env.DB.prepare(`INSERT INTO deal_commission_splits (id,agency_id,deal_id,user_id,basis_points,amount_minor,finalized_at) VALUES (?,?,?,?,?,?,CURRENT_TIMESTAMP)`).bind(crypto.randomUUID(),agencyId,dealB,user.userId,10000,540000),
  env.DB.prepare(`INSERT INTO public_events (id,agency_id,property_id,event_type,session_hash,created_at) VALUES (?,?,?,?,?,?)`).bind(crypto.randomUUID(),agencyId,propertyA,"property_view","local-preview-a",iso(-2*day)),
  env.DB.prepare(`INSERT INTO public_events (id,agency_id,property_id,event_type,session_hash,created_at) VALUES (?,?,?,?,?,?)`).bind(crypto.randomUUID(),agencyId,propertyA,"property_view","local-preview-b",iso(-day)),
  env.DB.prepare(`INSERT INTO seller_reports (id,agency_id,property_id,period_start,period_end,views,enquiries,viewings,offers,momentum,summary,recommended_action,status,created_by,approved_by,approved_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(reportId,agencyId,propertyA,iso(-7*day),iso(0),24,6,3,1,"Strong buyer intent","Borrowdale Residence is attracting qualified demand, with one active offer conversation and strong viewing conversion.","Keep the asking price steady this week and prioritise qualified second viewings.","approved",user.userId,user.userId,iso(-2*60*60000)),
  env.DB.prepare(`INSERT INTO seller_access_grants (id,agency_id,property_id,contact_id,email,token_hash,expires_at,accepted_user_id,accepted_at,invited_by) VALUES (?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP,?)`).bind(grantId,agencyId,propertyA,contactSeller,user.email,`local-preview-${grantId}`,iso(30*day),user.userId,user.userId),
  env.DB.prepare(`INSERT INTO contact_activities (id,agency_id,contact_id,actor_user_id,activity_type,summary,resource_type,resource_id) VALUES (?,?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),agencyId,contactBuyer,user.userId,"enquiry.created","Qualified enquiry recorded for Borrowdale Residence","enquiry",enquiryA),
  env.DB.prepare(`INSERT INTO contact_activities (id,agency_id,contact_id,actor_user_id,activity_type,summary,resource_type,resource_id) VALUES (?,?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),agencyId,contactTenant,user.userId,"viewing.requested","Viewing requested for Newlands Executive Townhouse","viewing",enquiryB),
  env.DB.prepare(`INSERT INTO audit_logs (id,agency_id,actor_user_id,action,resource_type,resource_id,detail) VALUES (?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),agencyId,user.userId,"local_preview.seeded","agency",agencyId,JSON.stringify({properties:3,enquiries:2,deals:2}))
 ]);
 await ensureLocalPreviewSellerAccess(agencyId,user);
}

async function ensureLocalPreviewSellerAccess(agencyId:string,user:ChatGPTUser){
 const existing=await env.DB.prepare("SELECT id FROM seller_access_grants WHERE agency_id=? AND accepted_user_id=? AND accepted_at IS NOT NULL AND revoked_at IS NULL LIMIT 1").bind(agencyId,user.userId).first();
 if(existing)return;
 const property=await env.DB.prepare("SELECT id FROM properties WHERE agency_id=? ORDER BY created_at LIMIT 1").bind(agencyId).first<{id:string}>();
 if(!property)return;
 const seller=await env.DB.prepare("SELECT id FROM contacts WHERE agency_id=? AND email_normalized=? LIMIT 1").bind(agencyId,user.email).first<{id:string}>();
 const report=await env.DB.prepare("SELECT id FROM seller_reports WHERE agency_id=? AND property_id=? AND status='approved' LIMIT 1").bind(agencyId,property.id).first();
 const now=Date.now(),day=86400000,iso=(offset:number)=>new Date(now+offset).toISOString(),grantId=crypto.randomUUID();
 const statements=[
  env.DB.prepare(`INSERT INTO seller_access_grants (id,agency_id,property_id,contact_id,email,token_hash,expires_at,accepted_user_id,accepted_at,invited_by) VALUES (?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP,?)`).bind(grantId,agencyId,property.id,seller?.id||null,user.email,`local-preview-${grantId}`,iso(30*day),user.userId,user.userId)
 ];
 if(!report)statements.push(env.DB.prepare(`INSERT INTO seller_reports (id,agency_id,property_id,period_start,period_end,views,enquiries,viewings,offers,momentum,summary,recommended_action,status,created_by,approved_by,approved_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),agencyId,property.id,iso(-7*day),iso(0),24,6,3,1,"Strong buyer intent","This property is attracting qualified demand and has enough activity for a credible seller update.","Keep qualified follow-up tight and prioritise confirmed second viewings.","approved",user.userId,user.userId,iso(-2*60*60000)));
 await env.DB.batch(statements);
}
