"use client";
import { FormEvent,useEffect,useState } from "react";
export default function DocumentsClient(){
 const[docs,setDocs]=useState<any[]>([]),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[grant,setGrant]=useState<Record<string,string>>({});
 const load=()=>fetch("/api/documents").then(r=>r.json()).then(j=>setDocs(j.documents||[]));useEffect(()=>{load()},[]);
 async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const r=await fetch("/api/documents",{method:"POST",body:new FormData(e.currentTarget)}),j=await r.json();setNotice(r.ok?"Document stored securely.":j.error);if(r.ok){e.currentTarget.reset();load()}setBusy(false)}
 async function link(id:string){const r=await fetch("/api/documents",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id})}),j=await r.json();if(r.ok){await navigator.clipboard.writeText(location.origin+j.url);setNotice("Single-use 15-minute access link copied.")}else setNotice(j.error)}
 async function allow(id:string){const subjectId=(grant[id]||"").trim();if(!subjectId)return setNotice("Enter the member user ID to grant access.");const r=await fetch("/api/documents",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action:"grant",id,subjectType:"user",subjectId,capability:"read"})}),j=await r.json();setNotice(r.ok?"Restricted access granted and audited.":j.error);if(r.ok)load()}
 async function remove(id:string){if(!confirm("Remove this document permanently?"))return;const r=await fetch(`/api/documents?id=${id}`,{method:"DELETE"});if(r.ok){setNotice("Document removed.");load()}}
 return <main className="tool-page"><a className="back" href="/">← Workspace</a><section className="tool-hero"><span>Private document vault</span><h1>Records protected by design.</h1><p>Agency-isolated storage, user-level grants, branch-aware access and expiring single-use links.</p></section><form className="upload-card" onSubmit={upload}><label>Document title<input name="title" required minLength={2} placeholder="Signed sole mandate"/></label><label>Category<select name="category"><option>Mandate</option><option>Offer</option><option>Identity</option><option>Contract</option><option>Inspection</option><option>Other</option></select></label><label>Access<select name="accessMode" defaultValue="agency"><option value="agency">Agency members</option><option value="restricted">Restricted — grant explicitly</option></select></label><label>File<input name="file" type="file" accept=".pdf,.docx,.xlsx,.jpg,.jpeg,.png" required/></label><button disabled={busy}>{busy?"Securing…":"Secure upload"}</button></form>{notice&&<div className="notice" role="status">{notice}</div>}<section className="doc-grid">{docs.map(d=><article key={d.id}><i>{d.mimeType.includes("pdf")?"PDF":"FILE"}</i><small>{d.category} · {d.accessMode==="restricted"?"RESTRICTED":"AGENCY"}</small><h3>{d.title}</h3><p>{d.originalName} · {(d.byteSize/1024).toFixed(0)} KB</p>{d.accessMode==="restricted"&&<label>Grant member by user ID<input value={grant[d.id]||""} onChange={e=>setGrant({...grant,[d.id]:e.target.value})} placeholder="Member user ID"/><button onClick={()=>allow(d.id)} type="button">Grant read access</button></label>}<footer><button onClick={()=>link(d.id)}>Copy secure link</button><button className="danger" onClick={()=>remove(d.id)}>Remove</button></footer></article>)}{!docs.length&&<p>No private documents are available to you.</p>}</section></main>;
}
