import { env } from "cloudflare:workers";
export const dynamic="force-dynamic";

const encoder=new TextEncoder();
const hex=(bytes:ArrayBuffer)=>[...new Uint8Array(bytes)].map(byte=>byte.toString(16).padStart(2,"0")).join("");
async function sha256(value:string){return hex(await crypto.subtle.digest("SHA-256",encoder.encode(value)))}
async function hmac(secret:string,value:string){const key=await crypto.subtle.importKey("raw",encoder.encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return hex(await crypto.subtle.sign("HMAC",key,encoder.encode(value)))}
function signatureParts(header:string){const parts=Object.fromEntries(header.split(",").map(part=>part.split("=",2)).filter(pair=>pair.length===2) as [string,string][]);return{timestamp:parts.t,signature:parts.v1}}
function safeEqualHex(a:string,b:string){if(a.length!==b.length)return false;let diff=0;for(let index=0;index<a.length;index++)diff|=a.charCodeAt(index)^b.charCodeAt(index);return diff===0}
async function billingEvent(agencyId:string,subscriptionId:string|null,invoiceId:string|null,eventType:string,detail:Record<string,unknown>){await env.DB.prepare("INSERT INTO billing_events (id,agency_id,subscription_id,invoice_id,event_type,detail,actor_user_id) VALUES (?,?,?,?,?,?,?)").bind(crypto.randomUUID(),agencyId,subscriptionId,invoiceId,eventType,JSON.stringify(detail),"stripe-webhook").run()}
async function activatePaidSubscription(paymentRequestId:string,eventId:string){const row=await env.DB.prepare("SELECT r.id,r.status,r.agency_id AS agencyId,r.subscription_id AS subscriptionId,r.invoice_id AS invoiceId,r.plan_version_id AS planVersionId,r.provider,r.period_starts_at AS periodStartsAt,r.period_ends_at AS periodEndsAt FROM billing_payment_requests r WHERE r.id=?").bind(paymentRequestId).first<any>();if(!row)return{activated:false,reason:"payment request not found"};if(row.status==="approved")return{activated:true,duplicate:true};await env.DB.batch([env.DB.prepare("UPDATE billing_payment_requests SET status='approved',reviewed_by='stripe-webhook',reviewed_at=CURRENT_TIMESTAMP,external_event_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status<>'approved'").bind(eventId,paymentRequestId),env.DB.prepare("UPDATE billing_invoices SET status='paid',paid_at=CURRENT_TIMESTAMP,payment_method='stripe',provider_reference=? WHERE id=? AND status='open'").bind(eventId,row.invoiceId),env.DB.prepare("UPDATE agency_subscriptions SET state='active',plan_version_id=?,payment_provider='stripe',grace_ends_at=NULL,suspended_at=NULL,canceled_at=NULL,expired_at=NULL,status_reason='',current_period_starts_at=COALESCE(?,CURRENT_TIMESTAMP),current_period_ends_at=?,updated_by='stripe-webhook',updated_at=CURRENT_TIMESTAMP WHERE id=? AND state<>'canceled'").bind(row.planVersionId,row.periodStartsAt,row.periodEndsAt,row.subscriptionId)]);await billingEvent(row.agencyId,row.subscriptionId,row.invoiceId,"payment.stripe_approved",{paymentRequestId,eventId});return{activated:true}}
async function closeStripeRequest(paymentRequestId:string,eventId:string,status:"expired"|"rejected",reason:string){const row=await env.DB.prepare("SELECT id,status,agency_id AS agencyId,subscription_id AS subscriptionId,invoice_id AS invoiceId FROM billing_payment_requests WHERE id=?").bind(paymentRequestId).first<any>();if(!row)return{closed:false,reason:"payment request not found"};if(["approved","cancelled","expired"].includes(row.status))return{closed:true,duplicate:true,status:row.status};await env.DB.batch([env.DB.prepare("UPDATE billing_payment_requests SET status=?,reviewed_by='stripe-webhook',reviewed_at=CURRENT_TIMESTAMP,rejection_reason=?,external_event_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status NOT IN ('approved','cancelled','expired')").bind(status,reason,eventId,paymentRequestId),env.DB.prepare("UPDATE billing_invoices SET status=? WHERE id=? AND status='open'").bind(status==="expired"?"cancelled":"open",row.invoiceId),env.DB.prepare("UPDATE agency_subscriptions SET state='pending_payment',status_reason=?,updated_by='stripe-webhook',updated_at=CURRENT_TIMESTAMP WHERE id=? AND state NOT IN ('active','trialing','free','canceled')").bind(reason,row.subscriptionId)]);await billingEvent(row.agencyId,row.subscriptionId,row.invoiceId,status==="expired"?"payment.stripe_expired":"payment.stripe_failed",{paymentRequestId,eventId,reason});return{closed:true,status}}

export async function POST(request:Request){const secret=(env as any).STRIPE_WEBHOOK_SECRET as string|undefined;if(!secret)return Response.json({error:"Stripe webhook secret is not configured."},{status:503});const raw=await request.text(),header=request.headers.get("stripe-signature")||"",parts=signatureParts(header);if(!parts.timestamp||!parts.signature)return Response.json({error:"Missing Stripe signature."},{status:400});const expected=await hmac(secret,`${parts.timestamp}.${raw}`);if(!safeEqualHex(expected,parts.signature))return Response.json({error:"Invalid Stripe signature."},{status:400});const event=JSON.parse(raw),eventId=String(event.id||"");if(!eventId)return Response.json({error:"Stripe event id is required."},{status:400});const payloadHash=await sha256(raw),existing=await env.DB.prepare("SELECT id,status FROM billing_webhook_events WHERE provider='stripe' AND event_id=?").bind(eventId).first<any>();if(existing)return Response.json({received:true,duplicate:true});let detail:Record<string,unknown>={type:event.type};if(event.type==="checkout.session.completed"){const session=event.data?.object||{},paymentRequestId=String(session.metadata?.paymentRequestId||"");if(session.payment_status==="paid"&&paymentRequestId)detail={...detail,...await activatePaidSubscription(paymentRequestId,eventId)}}else if(event.type==="checkout.session.expired"){const session=event.data?.object||{},paymentRequestId=String(session.metadata?.paymentRequestId||"");if(paymentRequestId)detail={...detail,...await closeStripeRequest(paymentRequestId,eventId,"expired","Stripe Checkout session expired before payment.")}}else if(event.type==="payment_intent.payment_failed"||event.type==="invoice.payment_failed"){const object=event.data?.object||{},paymentRequestId=String(object.metadata?.paymentRequestId||"");if(paymentRequestId)detail={...detail,...await closeStripeRequest(paymentRequestId,eventId,"rejected","Stripe reported a failed payment.")}}
await env.DB.prepare("INSERT INTO billing_webhook_events (id,provider,event_id,payload_hash,status,detail) VALUES (?,?,?,?,?,?)").bind(crypto.randomUUID(),"stripe",eventId,payloadHash,"processed",JSON.stringify(detail)).run();return Response.json({received:true,detail})}
