import { env } from "cloudflare:workers";
import { getChatGPTUser } from "../../chatgpt-auth";
import { calculateCompleteness,requireWorkspace } from "../../../db/workspace";
export const dynamic="force-dynamic";
const unauthorized=()=>Response.json({error:"Sign in is required."},{status:401});
const clean=(v:unknown,max=180)=>typeof v==="string"?v.trim().slice(0,max):"";
export async function GET(){const user=await getChatGPTUser();if(!user)return unauthorized();const w=await requireWorkspace(user);const [ps,es,as]=await Promise.all([env.DB.prepare(`SELECT id,reference AS ref,title,location,price_label AS price,bedrooms AS beds,bathrooms AS baths,status,photo_count AS photos,owner_phone AS owner,land_size AS size,completeness FROM properties WHERE agency_id=? ORDER BY created_at ASC`).bind(w.agencyId).all(),env.DB.prepare(`SELECT id,contact_name AS name,initials,property_label AS property,status,response_due_at AS responseDueAt,created_at AS createdAt FROM enquiries WHERE agency_id=? ORDER BY created_at DESC`).bind(w.agencyId).all(),env.DB.prepare(`SELECT COUNT(*) AS count FROM next_actions WHERE agency_id=? AND status='open'`).bind(w.agencyId).first<{count:number}>()]);return Response.json({agency:{id:w.agencyId,name:w.agencyName},properties:ps.results,enquiries:es.results,openActionCount:as?.count??0})}
export async function POST(request:Request){
 const user=await getChatGPTUser();if(!user)return unauthorized();const w=await requireWorkspace(user),b=await request.json() as Record<string,unknown>;
 if(b.kind==="enquiry"){
  const name=clean(b.name,100),propertyId=clean(b.propertyId,80),note=clean(b.note,500);if(!name||!propertyId)return Response.json({error:"Client and property are required."},{status:400});
  const property=await env.DB.prepare(`SELECT id,title FROM properties WHERE id=? AND agency_id=?`).bind(propertyId,w.agencyId).first<{id:string;title:string}>();if(!property)return Response.json({error:"Property was not found."},{status:404});
  const id=crypto.randomUUID(),initials=name.split(/\s+/).slice(0,2).map(x=>x[0]?.toUpperCase()).join(""),due=new Date(Date.now()+30*60000).toISOString();
  await env.DB.batch([env.DB.prepare(`INSERT INTO enquiries (id,agency_id,property_id,contact_name,initials,property_label,status,source,response_due_at) VALUES (?,?,?,?,?,?,'New','Manual',?)`).bind(id,w.agencyId,property.id,name,initials,property.title,due),env.DB.prepare(`INSERT INTO next_actions (id,agency_id,resource_type,resource_id,action_type,reason,priority,due_at,status,assigned_user_id) VALUES (?,?,'enquiry',?,'respond',?,'high',?,'open',?)`).bind(crypto.randomUUID(),w.agencyId,id,note||`Respond to ${name}`,due,user.userId)]);
  return Response.json({enquiry:{id,name,initials,property:property.title,status:"New",time:"Just now"}},{status:201});
 }
 const title=clean(b.title),location=clean(b.location),owner=clean(b.owner),size=clean(b.size);const priceMinor=Math.round(Number(b.priceMinor)),beds=Math.max(0,Math.round(Number(b.beds))),baths=Math.max(0,Math.round(Number(b.baths))),photos=Math.max(0,Math.round(Number(b.photos)));if(!title||!location||!Number.isSafeInteger(priceMinor)||priceMinor<=0)return Response.json({error:"Title, location and a valid price are required."},{status:400});const completeness=calculateCompleteness({title,location,priceMinor,bedrooms:beds,bathrooms:baths,photoCount:photos,ownerPhone:owner,landSize:size}),id=crypto.randomUUID(),ref=`EST-${String(Date.now()).slice(-4)}`,price=`US$${(priceMinor/100).toLocaleString("en-US")}`;await env.DB.prepare(`INSERT INTO properties (id,agency_id,reference,title,location,price_minor,currency,price_label,bedrooms,bathrooms,status,photo_count,owner_phone,land_size,completeness,created_by) VALUES (?,?,?,?,?,?,'USD',?,?,?,'Draft',?,?,?,?,?)`).bind(id,w.agencyId,ref,title,location,priceMinor,price,beds,baths,photos,owner,size,completeness,user.userId).run();return Response.json({property:{id,ref,title,location,price,beds,baths,status:"Draft",photos,owner,size,completeness}},{status:201})}
